// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module pointpillars_cnn_pointpillars_cnn_PointXYZI_int_BBox3D_int_ap_fixed_4_3_3_ap_fixed_ap_349_RAM_fYi (
    address0, ce0,
    d0, we0,
    q0,
    reset, clk);

parameter DataWidth = 6;
parameter AddressWidth = 6;
parameter AddressRange = 64;

input [AddressWidth-1:0] address0;
input ce0;
input [DataWidth-1:0] d0;
input we0;
output reg [DataWidth-1:0] q0;
input reset;
input clk;

(* ram_style = "auto" *) reg [DataWidth-1:0] ram[0:AddressRange-1];

initial begin
    $readmemh("./pointpillars_cnn_pointpillars_cnn_PointXYZI_int_BBox3D_int_ap_fixed_4_3_3_ap_fixed_ap_349_RAM_fYi.dat", ram);
end

// read first
always @(posedge clk)
begin
    if (ce0)
    begin
        if (we0)
            ram[address0] <= d0;
        q0 <= ram[address0];
    end
end


endmodule

