-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\proj_model\Grid_Locator.vhd
-- Created: 2025-12-16 23:56:31
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Grid_Locator
-- Source Path: proj_model/Subsystem/Grid Locator
-- Hierarchy Level: 1
-- Model version: 1.259
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_pkg.ALL;

ENTITY Grid_Locator IS
  PORT( point                             :   IN    vector_of_std_logic_vector8(0 TO 3);  -- uint8 [4]
        addr_index                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END Grid_Locator;


ARCHITECTURE rtl OF Grid_Locator IS

  -- Signals
  SIGNAL point_unsigned                   : vector_of_unsigned8(0 TO 3);  -- uint8 [4]
  SIGNAL addr_index_tmp                   : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL x                                : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL y                                : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL add_cast                         : signed(16 DOWNTO 0);  -- sfix17_E8
  SIGNAL add_cast_1                       : signed(48 DOWNTO 0);  -- sfix49
  SIGNAL add_cast_2                       : signed(31 DOWNTO 0);  -- int32
  SIGNAL add_cast_3                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL add_cast_4                       : signed(31 DOWNTO 0);  -- int32
  SIGNAL add_cast_5                       : signed(31 DOWNTO 0);  -- int32
  SIGNAL add_temp                         : signed(31 DOWNTO 0);  -- int32
  SIGNAL cast                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL mul_temp                         : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL cast_1                           : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL mul_temp_1                       : unsigned(31 DOWNTO 0);  -- ufix32

BEGIN
  outputgen: FOR k IN 0 TO 3 GENERATE
    point_unsigned(k) <= unsigned(point(k));
  END GENERATE;

  x <= resize(point_unsigned(0), 16);
  y <= resize(point_unsigned(1), 16);
  add_cast <= signed(resize(y, 17));
  add_cast_1 <= resize(add_cast & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 49);
  add_cast_2 <= add_cast_1(31 DOWNTO 0);
  add_cast_3 <= unsigned(add_cast_2(15 DOWNTO 0));
  add_cast_4 <= signed(resize(add_cast_3, 32));
  add_cast_5 <= signed(resize(x, 32));
  add_temp <= add_cast_4 + add_cast_5;
  cast <= unsigned(add_temp(15 DOWNTO 0));
  -- CSD Encoding (64) : 1000000; Cost (Adders) = 0
  mul_temp <= resize(cast & '0' & '0' & '0' & '0' & '0' & '0', 32);
  
  cast_1 <= X"FFFF" WHEN mul_temp(31 DOWNTO 16) /= X"0000" ELSE
      mul_temp(15 DOWNTO 0);
  mul_temp_1 <= cast_1 * 9;
  
  addr_index_tmp <= X"FFFF" WHEN mul_temp_1(31 DOWNTO 16) /= X"0000" ELSE
      mul_temp_1(15 DOWNTO 0);

  addr_index <= std_logic_vector(addr_index_tmp);

END rtl;

