-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\proj_model\proj_model_pkg.vhd
-- Created: 2025-12-16 23:55:07
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE proj_model_pkg IS
  TYPE vector_of_std_logic_vector8 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(7 DOWNTO 0);
END proj_model_pkg;

