-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\proj_model\proj_model.vhd
-- Created: 2025-12-16 23:55:07
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: proj_model
-- Source Path: proj_model
-- Hierarchy Level: 0
-- Model version: 1.258
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.proj_model_pkg.ALL;

ENTITY proj_model IS
  PORT( points                            :   IN    vector_of_std_logic_vector8(0 TO 3)  -- uint8 [4]
        );
END proj_model;


ARCHITECTURE rtl OF proj_model IS

BEGIN
  -- U(k)
  -- Edge


END rtl;

