-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\proj_model\Subsystem.vhd
-- Created: 2025-12-16 23:56:31
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out_1      0
-- ce_out_0      0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out_0      inf
-- U                             ce_out_0      0.2
-- Y                             ce_out_0      0.2
-- addr_index                    ce_out_1      0
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: proj_model/Subsystem
-- Hierarchy Level: 0
-- Model version: 1.259
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_pkg.ALL;

ENTITY Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        point                             :   IN    vector_of_std_logic_vector8(0 TO 3);  -- uint8 [4]
        In2                               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        ce_out_0                          :   OUT   std_logic;
        ce_out_1                          :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        U                                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        Y                                 :   OUT   std_logic;
        addr_index                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Component Declarations
  COMPONENT Grid_Locator
    PORT( point                           :   IN    vector_of_std_logic_vector8(0 TO 3);  -- uint8 [4]
          addr_index                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Grid_Locator
    USE ENTITY work.Grid_Locator(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL In2_unsigned                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Sum_out1                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL addr_index_tmp                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL addr_index_tmp_unsigned          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_out1                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL U_k_1                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FixPt_Relational_Operator_out1   : std_logic;

BEGIN
  -- U(k)
  -- Edge

  u_Grid_Locator : Grid_Locator
    PORT MAP( point => point,  -- uint8 [4]
              addr_index => addr_index_tmp  -- uint16
              );

  Constant_out1 <= to_unsigned(16#0001#, 16);

  In2_unsigned <= unsigned(In2);

  Sum_out1 <= Constant_out1 + In2_unsigned;

  Out1 <= std_logic_vector(Sum_out1);

  addr_index_tmp_unsigned <= unsigned(addr_index_tmp);

  enb <= clk_enable;

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= addr_index_tmp_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  U <= std_logic_vector(Unit_Delay_out1);

  -- 
  -- Store in Global RAM
  Delay_Input1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      U_k_1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        U_k_1 <= Unit_Delay_out1;
      END IF;
    END IF;
  END PROCESS Delay_Input1_process;


  
  FixPt_Relational_Operator_out1 <= '1' WHEN Unit_Delay_out1 /= U_k_1 ELSE
      '0';

  Y <= FixPt_Relational_Operator_out1;

  ce_out_0 <= clk_enable;

  ce_out_1 <= clk_enable;

  addr_index <= addr_index_tmp;

END rtl;

