-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculate_pseudoimage_calculate_pseudoimage_Pipeline_assign_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pseudoimage_count_load : IN STD_LOGIC_VECTOR (31 downto 0);
    empty : IN STD_LOGIC_VECTOR (19 downto 0);
    pseudoimage_data_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    pseudoimage_data_ce0 : OUT STD_LOGIC;
    pseudoimage_data_we0 : OUT STD_LOGIC;
    pseudoimage_data_d0 : OUT STD_LOGIC_VECTOR (575 downto 0);
    pseudoimage_data_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    pseudoimage_data_ce1 : OUT STD_LOGIC;
    pseudoimage_data_q1 : IN STD_LOGIC_VECTOR (575 downto 0);
    avg_x : IN STD_LOGIC_VECTOR (63 downto 0);
    avg_y : IN STD_LOGIC_VECTOR (63 downto 0);
    avg_z : IN STD_LOGIC_VECTOR (63 downto 0);
    div5 : IN STD_LOGIC_VECTOR (63 downto 0);
    div6 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_406_p_din0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_406_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_406_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_406_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_406_p_ce : OUT STD_LOGIC );
end;


architecture behav of calculate_pseudoimage_calculate_pseudoimage_Pipeline_assign_loop is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln69_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal pseudoimage_data_addr_reg_302 : STD_LOGIC_VECTOR (19 downto 0);
    signal pseudoimage_data_addr_reg_302_pp0_iter1_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal pseudoimage_data_addr_reg_302_pp0_iter2_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal pseudoimage_data_addr_reg_302_pp0_iter3_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal pseudoimage_data_addr_reg_302_pp0_iter4_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln70_1_fu_185_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal trunc_ln70_1_reg_308 : STD_LOGIC_VECTOR (255 downto 0);
    signal trunc_ln70_1_reg_308_pp0_iter2_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal trunc_ln70_1_reg_308_pp0_iter3_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal trunc_ln70_1_reg_308_pp0_iter4_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal bitcast_ln70_fu_193_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln71_fu_209_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln70_fu_175_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_1_fu_58 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    signal add_ln69_fu_159_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j : STD_LOGIC_VECTOR (20 downto 0);
    signal pseudoimage_data_ce1_local : STD_LOGIC;
    signal pseudoimage_data_we0_local : STD_LOGIC;
    signal or_ln75_4_fu_250_p7 : STD_LOGIC_VECTOR (575 downto 0);
    signal pseudoimage_data_ce0_local : STD_LOGIC;
    signal grp_fu_129_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln69_fu_149_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln70_fu_165_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln70_fu_169_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln70_2_fu_189_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln5_fu_199_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln6_fu_215_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_125_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_129_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_133_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_137_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln75_fu_246_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln74_fu_242_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln72_1_fu_238_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln71_1_fu_234_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln70_1_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calculate_pseudoimage_dadddsub_64ns_64ns_64_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculate_pseudoimage_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    dsub_64ns_64ns_64_5_full_dsp_1_U19 : component calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => bitcast_ln71_fu_209_p1,
        din1 => avg_y,
        ce => ap_const_logic_1,
        dout => grp_fu_125_p2);

    dsub_64ns_64ns_64_5_full_dsp_1_U20 : component calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_129_p0,
        din1 => avg_z,
        ce => ap_const_logic_1,
        dout => grp_fu_129_p2);

    dsub_64ns_64ns_64_5_full_dsp_1_U21 : component calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => bitcast_ln70_fu_193_p1,
        din1 => div5,
        ce => ap_const_logic_1,
        dout => grp_fu_133_p2);

    dsub_64ns_64ns_64_5_full_dsp_1_U22 : component calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => bitcast_ln71_fu_209_p1,
        din1 => div6,
        ce => ap_const_logic_1,
        dout => grp_fu_137_p2);

    flow_control_loop_pipe_sequential_init_U : component calculate_pseudoimage_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    j_1_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln69_fu_153_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_1_fu_58 <= add_ln69_fu_159_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_1_fu_58 <= ap_const_lv21_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                pseudoimage_data_addr_reg_302 <= zext_ln70_fu_175_p1(20 - 1 downto 0);
                pseudoimage_data_addr_reg_302_pp0_iter1_reg <= pseudoimage_data_addr_reg_302;
                trunc_ln70_1_reg_308 <= trunc_ln70_1_fu_185_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                pseudoimage_data_addr_reg_302_pp0_iter2_reg <= pseudoimage_data_addr_reg_302_pp0_iter1_reg;
                pseudoimage_data_addr_reg_302_pp0_iter3_reg <= pseudoimage_data_addr_reg_302_pp0_iter2_reg;
                pseudoimage_data_addr_reg_302_pp0_iter4_reg <= pseudoimage_data_addr_reg_302_pp0_iter3_reg;
                trunc_ln70_1_reg_308_pp0_iter2_reg <= trunc_ln70_1_reg_308;
                trunc_ln70_1_reg_308_pp0_iter3_reg <= trunc_ln70_1_reg_308_pp0_iter2_reg;
                trunc_ln70_1_reg_308_pp0_iter4_reg <= trunc_ln70_1_reg_308_pp0_iter3_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln69_fu_159_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j) + unsigned(ap_const_lv21_1));
    add_ln70_fu_169_p2 <= std_logic_vector(unsigned(empty) + unsigned(trunc_ln70_fu_165_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln69_fu_153_p2)
    begin
        if (((icmp_ln69_fu_153_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_1_fu_58, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j <= ap_const_lv21_0;
        else 
            ap_sig_allocacmp_j <= j_1_fu_58;
        end if; 
    end process;

    bitcast_ln70_1_fu_230_p1 <= grp_fu_406_p_dout0;
    bitcast_ln70_fu_193_p1 <= trunc_ln70_2_fu_189_p1;
    bitcast_ln71_1_fu_234_p1 <= grp_fu_125_p2;
    bitcast_ln71_fu_209_p1 <= trunc_ln5_fu_199_p4;
    bitcast_ln72_1_fu_238_p1 <= grp_fu_129_p2;
    bitcast_ln74_fu_242_p1 <= grp_fu_133_p2;
    bitcast_ln75_fu_246_p1 <= grp_fu_137_p2;
    grp_fu_129_p0 <= trunc_ln6_fu_215_p4;
    grp_fu_406_p_ce <= ap_const_logic_1;
    grp_fu_406_p_din0 <= bitcast_ln70_fu_193_p1;
    grp_fu_406_p_din1 <= avg_x;
    grp_fu_406_p_opcode <= ap_const_lv2_1(1 - 1 downto 0);
    icmp_ln69_fu_153_p2 <= "1" when (zext_ln69_fu_149_p1 = pseudoimage_count_load) else "0";
    or_ln75_4_fu_250_p7 <= (((((bitcast_ln75_fu_246_p1 & bitcast_ln74_fu_242_p1) & bitcast_ln72_1_fu_238_p1) & bitcast_ln71_1_fu_234_p1) & bitcast_ln70_1_fu_230_p1) & trunc_ln70_1_reg_308_pp0_iter4_reg);
    pseudoimage_data_address0 <= pseudoimage_data_addr_reg_302_pp0_iter4_reg;
    pseudoimage_data_address1 <= zext_ln70_fu_175_p1(20 - 1 downto 0);
    pseudoimage_data_ce0 <= pseudoimage_data_ce0_local;

    pseudoimage_data_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pseudoimage_data_ce0_local <= ap_const_logic_1;
        else 
            pseudoimage_data_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pseudoimage_data_ce1 <= pseudoimage_data_ce1_local;

    pseudoimage_data_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pseudoimage_data_ce1_local <= ap_const_logic_1;
        else 
            pseudoimage_data_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pseudoimage_data_d0 <= or_ln75_4_fu_250_p7;
    pseudoimage_data_we0 <= pseudoimage_data_we0_local;

    pseudoimage_data_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pseudoimage_data_we0_local <= ap_const_logic_1;
        else 
            pseudoimage_data_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln5_fu_199_p4 <= pseudoimage_data_q1(127 downto 64);
    trunc_ln6_fu_215_p4 <= pseudoimage_data_q1(191 downto 128);
    trunc_ln70_1_fu_185_p1 <= pseudoimage_data_q1(256 - 1 downto 0);
    trunc_ln70_2_fu_189_p1 <= pseudoimage_data_q1(64 - 1 downto 0);
    trunc_ln70_fu_165_p1 <= ap_sig_allocacmp_j(20 - 1 downto 0);
    zext_ln69_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j),32));
    zext_ln70_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_fu_169_p2),64));
end behav;
