# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline calculate_pseudoimage/anonymous
set_directive_pipeline calculate_pseudoimage/collection_loop
set_directive_pipeline calculate_pseudoimage/assign_loop
set_directive_pipeline calculate_pseudoimage/sum_loop
