-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\proj_model\Adder.vhd
-- Created: 2025-12-15 14:29:15
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: inf
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Adder
-- Source Path: proj_model/Adder
-- Hierarchy Level: 0
-- Model version: 1.20
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Adder IS
  PORT( In1                               :   IN    std_logic_vector(1 DOWNTO 0);  -- boolean [2]
        Out1                              :   OUT   std_logic
        );
END Adder;


ARCHITECTURE rtl OF Adder IS

  -- Signals
  SIGNAL In1_0                            : std_logic;
  SIGNAL In1_1                            : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;

BEGIN
  In1_0 <= In1(0);

  In1_1 <= In1(1);

  Logical_Operator_out1 <= In1_0 XOR In1_1;

  Out1 <= Logical_Operator_out1;

END rtl;

