-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculate_pseudoimage is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pointcloud_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pointcloud_ce0 : OUT STD_LOGIC;
    pointcloud_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    pseudoimage_count_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    pseudoimage_count_ce0 : OUT STD_LOGIC;
    pseudoimage_count_we0 : OUT STD_LOGIC;
    pseudoimage_count_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    pseudoimage_count_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    pseudoimage_data_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    pseudoimage_data_ce0 : OUT STD_LOGIC;
    pseudoimage_data_we0 : OUT STD_LOGIC;
    pseudoimage_data_d0 : OUT STD_LOGIC_VECTOR (575 downto 0);
    pseudoimage_data_q0 : IN STD_LOGIC_VECTOR (575 downto 0);
    pseudoimage_data_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    pseudoimage_data_ce1 : OUT STD_LOGIC;
    pseudoimage_data_q1 : IN STD_LOGIC_VECTOR (575 downto 0) );
end;


architecture behav of calculate_pseudoimage is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "calculate_pseudoimage_calculate_pseudoimage,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku025-ffva1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.676000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=5034,HLS_SYN_LUT=9920,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (34 downto 0) := "00000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (34 downto 0) := "00000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (34 downto 0) := "00000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (34 downto 0) := "00000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (34 downto 0) := "00000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (34 downto 0) := "00000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (34 downto 0) := "00001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (34 downto 0) := "00010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (34 downto 0) := "00100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (34 downto 0) := "01000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (34 downto 0) := "10000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv64_407F400000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0100000001111111010000000000000000000000000000000000000000000000";
    constant ap_const_lv64_3F80000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0011111110000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_162_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal reg_193 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal ap_CS_fsm_state33 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state33 : signal is "none";
    signal grp_fu_167_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal reg_199 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal x_reg_332 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal y_reg_337 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln60_fu_254_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln60_reg_342 : STD_LOGIC_VECTOR (13 downto 0);
    signal pseudoimage_count_load_reg_352 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_fu_265_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_reg_359 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_186_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal conv1_reg_365 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal conv2_reg_381 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal grp_fu_190_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal conv3_reg_386 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_174_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal avg_x_reg_391 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_178_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal avg_y_reg_396 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_182_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal avg_z_reg_401 : STD_LOGIC_VECTOR (63 downto 0);
    signal indices_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal indices_ce0 : STD_LOGIC;
    signal indices_we0 : STD_LOGIC;
    signal indices_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal indices_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal indices_first_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal indices_first_ce0 : STD_LOGIC;
    signal indices_first_we0 : STD_LOGIC;
    signal indices_first_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal indices_first_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_idle : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_ready : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_we0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_we0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_idle : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_ready : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_we0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_we0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_d0 : STD_LOGIC_VECTOR (575 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_we0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_we0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out_ap_vld : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_ce : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_ce : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_idle : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_ready : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out_ap_vld : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out_ap_vld : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out_ap_vld : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_opcode : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_ce : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_idle : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_ready : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_we0 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_d0 : STD_LOGIC_VECTOR (575 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address1 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce1 : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_opcode : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_ce : STD_LOGIC;
    signal grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg : STD_LOGIC := '0';
    signal grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state34 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state34 : signal is "none";
    signal ap_CS_fsm_state35 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state35 : signal is "none";
    signal zext_ln52_fu_227_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln52_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln60_fu_260_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_1_fu_52 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln52_fu_221_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal indices_ce0_local : STD_LOGIC;
    signal indices_first_ce0_local : STD_LOGIC;
    signal pseudoimage_count_ce0_local : STD_LOGIC;
    signal grp_fu_162_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal ap_CS_fsm_state29 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal grp_fu_167_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_167_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_174_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_174_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_186_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal trunc_ln53_fu_238_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_fu_242_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln60_fu_250_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_174_ce : STD_LOGIC;
    signal grp_fu_186_ce : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal grp_fu_406_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_406_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_406_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_406_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_406_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (34 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calculate_pseudoimage_calculate_pseudoimage_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        indices_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        indices_ce0 : OUT STD_LOGIC;
        indices_we0 : OUT STD_LOGIC;
        indices_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        indices_first_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        indices_first_ce0 : OUT STD_LOGIC;
        indices_first_we0 : OUT STD_LOGIC;
        indices_first_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calculate_pseudoimage_calculate_pseudoimage_Pipeline_collection_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pointcloud_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        pointcloud_ce0 : OUT STD_LOGIC;
        pointcloud_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
        pseudoimage_count_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        pseudoimage_count_ce0 : OUT STD_LOGIC;
        pseudoimage_count_we0 : OUT STD_LOGIC;
        pseudoimage_count_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        pseudoimage_count_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        pseudoimage_data_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        pseudoimage_data_ce0 : OUT STD_LOGIC;
        pseudoimage_data_we0 : OUT STD_LOGIC;
        pseudoimage_data_d0 : OUT STD_LOGIC_VECTOR (575 downto 0);
        pseudoimage_data_q0 : IN STD_LOGIC_VECTOR (575 downto 0);
        indices_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        indices_ce0 : OUT STD_LOGIC;
        indices_we0 : OUT STD_LOGIC;
        indices_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        indices_first_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        indices_first_ce0 : OUT STD_LOGIC;
        indices_first_we0 : OUT STD_LOGIC;
        indices_first_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        pillar_count_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pillar_count_out_ap_vld : OUT STD_LOGIC;
        grp_fu_174_p_din0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_174_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_174_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_174_p_ce : OUT STD_LOGIC;
        grp_fu_186_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_186_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_186_p_ce : OUT STD_LOGIC );
    end component;


    component calculate_pseudoimage_calculate_pseudoimage_Pipeline_sum_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pseudoimage_count_load : IN STD_LOGIC_VECTOR (31 downto 0);
        empty : IN STD_LOGIC_VECTOR (19 downto 0);
        pseudoimage_data_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        pseudoimage_data_ce0 : OUT STD_LOGIC;
        pseudoimage_data_q0 : IN STD_LOGIC_VECTOR (575 downto 0);
        avg_z_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        avg_z_1_out_ap_vld : OUT STD_LOGIC;
        avg_y_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        avg_y_1_out_ap_vld : OUT STD_LOGIC;
        avg_x_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        avg_x_1_out_ap_vld : OUT STD_LOGIC;
        grp_fu_406_p_din0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_406_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_406_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_406_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_406_p_ce : OUT STD_LOGIC );
    end component;


    component calculate_pseudoimage_calculate_pseudoimage_Pipeline_assign_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pseudoimage_count_load : IN STD_LOGIC_VECTOR (31 downto 0);
        empty : IN STD_LOGIC_VECTOR (19 downto 0);
        pseudoimage_data_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        pseudoimage_data_ce0 : OUT STD_LOGIC;
        pseudoimage_data_we0 : OUT STD_LOGIC;
        pseudoimage_data_d0 : OUT STD_LOGIC_VECTOR (575 downto 0);
        pseudoimage_data_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        pseudoimage_data_ce1 : OUT STD_LOGIC;
        pseudoimage_data_q1 : IN STD_LOGIC_VECTOR (575 downto 0);
        avg_x : IN STD_LOGIC_VECTOR (63 downto 0);
        avg_y : IN STD_LOGIC_VECTOR (63 downto 0);
        avg_z : IN STD_LOGIC_VECTOR (63 downto 0);
        div5 : IN STD_LOGIC_VECTOR (63 downto 0);
        div6 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_406_p_din0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_406_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_406_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_406_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_fu_406_p_ce : OUT STD_LOGIC );
    end component;


    component calculate_pseudoimage_dmul_64ns_64ns_64_5_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculate_pseudoimage_ddiv_64ns_64ns_64_22_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculate_pseudoimage_uitodp_32ns_64_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculate_pseudoimage_dadddsub_64ns_64ns_64_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculate_pseudoimage_indices_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    indices_U : component calculate_pseudoimage_indices_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 1000,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => indices_address0,
        ce0 => indices_ce0,
        we0 => indices_we0,
        d0 => indices_d0,
        q0 => indices_q0);

    indices_first_U : component calculate_pseudoimage_indices_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 1000,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => indices_first_address0,
        ce0 => indices_first_ce0,
        we0 => indices_first_we0,
        d0 => indices_first_d0,
        q0 => indices_first_q0);

    grp_calculate_pseudoimage_Pipeline_1_fu_117 : component calculate_pseudoimage_calculate_pseudoimage_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start,
        ap_done => grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done,
        ap_idle => grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_idle,
        ap_ready => grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_ready,
        indices_address0 => grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_address0,
        indices_ce0 => grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_ce0,
        indices_we0 => grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_we0,
        indices_d0 => grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_d0,
        indices_first_address0 => grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_address0,
        indices_first_ce0 => grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_ce0,
        indices_first_we0 => grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_we0,
        indices_first_d0 => grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_d0);

    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125 : component calculate_pseudoimage_calculate_pseudoimage_Pipeline_collection_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start,
        ap_done => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done,
        ap_idle => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_idle,
        ap_ready => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_ready,
        pointcloud_address0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_address0,
        pointcloud_ce0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_ce0,
        pointcloud_q0 => pointcloud_q0,
        pseudoimage_count_address0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_address0,
        pseudoimage_count_ce0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_ce0,
        pseudoimage_count_we0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_we0,
        pseudoimage_count_d0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_d0,
        pseudoimage_count_q0 => pseudoimage_count_q0,
        pseudoimage_data_address0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_address0,
        pseudoimage_data_ce0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_ce0,
        pseudoimage_data_we0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_we0,
        pseudoimage_data_d0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_d0,
        pseudoimage_data_q0 => pseudoimage_data_q0,
        indices_address0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_address0,
        indices_ce0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_ce0,
        indices_we0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_we0,
        indices_d0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_d0,
        indices_first_address0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_address0,
        indices_first_ce0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_ce0,
        indices_first_we0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_we0,
        indices_first_d0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_d0,
        pillar_count_out => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out,
        pillar_count_out_ap_vld => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out_ap_vld,
        grp_fu_174_p_din0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din0,
        grp_fu_174_p_din1 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din1,
        grp_fu_174_p_dout0 => grp_fu_174_p2,
        grp_fu_174_p_ce => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_ce,
        grp_fu_186_p_din0 => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_din0,
        grp_fu_186_p_dout0 => grp_fu_186_p1,
        grp_fu_186_p_ce => grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_ce);

    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138 : component calculate_pseudoimage_calculate_pseudoimage_Pipeline_sum_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start,
        ap_done => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done,
        ap_idle => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_idle,
        ap_ready => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_ready,
        pseudoimage_count_load => pseudoimage_count_load_reg_352,
        empty => tmp_reg_359,
        pseudoimage_data_address0 => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_address0,
        pseudoimage_data_ce0 => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_ce0,
        pseudoimage_data_q0 => pseudoimage_data_q0,
        avg_z_1_out => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out,
        avg_z_1_out_ap_vld => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out_ap_vld,
        avg_y_1_out => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out,
        avg_y_1_out_ap_vld => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out_ap_vld,
        avg_x_1_out => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out,
        avg_x_1_out_ap_vld => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out_ap_vld,
        grp_fu_406_p_din0 => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din0,
        grp_fu_406_p_din1 => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din1,
        grp_fu_406_p_opcode => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_opcode,
        grp_fu_406_p_dout0 => grp_fu_406_p2,
        grp_fu_406_p_ce => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_ce);

    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149 : component calculate_pseudoimage_calculate_pseudoimage_Pipeline_assign_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start,
        ap_done => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done,
        ap_idle => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_idle,
        ap_ready => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_ready,
        pseudoimage_count_load => pseudoimage_count_load_reg_352,
        empty => tmp_reg_359,
        pseudoimage_data_address0 => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address0,
        pseudoimage_data_ce0 => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce0,
        pseudoimage_data_we0 => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_we0,
        pseudoimage_data_d0 => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_d0,
        pseudoimage_data_address1 => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address1,
        pseudoimage_data_ce1 => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce1,
        pseudoimage_data_q1 => pseudoimage_data_q1,
        avg_x => avg_x_reg_391,
        avg_y => avg_y_reg_396,
        avg_z => avg_z_reg_401,
        div5 => reg_193,
        div6 => reg_199,
        grp_fu_406_p_din0 => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din0,
        grp_fu_406_p_din1 => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din1,
        grp_fu_406_p_opcode => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_opcode,
        grp_fu_406_p_dout0 => grp_fu_406_p2,
        grp_fu_406_p_ce => grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_ce);

    dmul_64ns_64ns_64_5_max_dsp_1_U32 : component calculate_pseudoimage_dmul_64ns_64ns_64_5_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_162_p0,
        din1 => grp_fu_162_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_162_p2);

    dmul_64ns_64ns_64_5_max_dsp_1_U33 : component calculate_pseudoimage_dmul_64ns_64ns_64_5_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_167_p0,
        din1 => grp_fu_167_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_167_p2);

    ddiv_64ns_64ns_64_22_no_dsp_1_U34 : component calculate_pseudoimage_ddiv_64ns_64ns_64_22_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 22,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_174_p0,
        din1 => grp_fu_174_p1,
        ce => grp_fu_174_ce,
        dout => grp_fu_174_p2);

    ddiv_64ns_64ns_64_22_no_dsp_1_U35 : component calculate_pseudoimage_ddiv_64ns_64ns_64_22_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 22,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out,
        din1 => conv1_reg_365,
        ce => ap_const_logic_1,
        dout => grp_fu_178_p2);

    ddiv_64ns_64ns_64_22_no_dsp_1_U36 : component calculate_pseudoimage_ddiv_64ns_64ns_64_22_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 22,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out,
        din1 => conv1_reg_365,
        ce => ap_const_logic_1,
        dout => grp_fu_182_p2);

    uitodp_32ns_64_4_no_dsp_1_U37 : component calculate_pseudoimage_uitodp_32ns_64_4_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_186_p0,
        ce => grp_fu_186_ce,
        dout => grp_fu_186_p1);

    uitodp_32ns_64_4_no_dsp_1_U38 : component calculate_pseudoimage_uitodp_32ns_64_4_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => y_reg_337,
        ce => ap_const_logic_1,
        dout => grp_fu_190_p1);

    dadddsub_64ns_64ns_64_5_full_dsp_1_U39 : component calculate_pseudoimage_dadddsub_64ns_64ns_64_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_406_p0,
        din1 => grp_fu_406_p1,
        opcode => grp_fu_406_opcode,
        ce => grp_fu_406_ce,
        dout => grp_fu_406_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_ready = ap_const_logic_1)) then 
                    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state34)) then 
                    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_ready = ap_const_logic_1)) then 
                    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_ready = ap_const_logic_1)) then 
                    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_ready = ap_const_logic_1)) then 
                    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_1_fu_52 <= ap_const_lv32_0;
            elsif (((icmp_ln52_fu_216_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                i_1_fu_52 <= add_ln52_fu_221_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln60_reg_342 <= add_ln60_fu_254_p2;
                x_reg_332 <= indices_q0;
                y_reg_337 <= indices_first_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state33)) then
                avg_x_reg_391 <= grp_fu_174_p2;
                avg_y_reg_396 <= grp_fu_178_p2;
                avg_z_reg_401 <= grp_fu_182_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                conv1_reg_365 <= grp_fu_186_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                conv2_reg_381 <= grp_fu_186_p1;
                conv3_reg_386 <= grp_fu_190_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                pseudoimage_count_load_reg_352 <= pseudoimage_count_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state28))) then
                reg_193 <= grp_fu_162_p2;
                reg_199 <= grp_fu_167_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                    tmp_reg_359(19 downto 6) <= tmp_fu_265_p3(19 downto 6);
            end if;
        end if;
    end process;
    tmp_reg_359(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state6, ap_CS_fsm_state11, grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state35, icmp_ln52_fu_216_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln52_fu_216_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                if (((grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state35))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state35;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln52_fu_221_p2 <= std_logic_vector(unsigned(i_1_fu_52) + unsigned(ap_const_lv32_1));
    add_ln60_fu_254_p2 <= std_logic_vector(unsigned(tmp_s_fu_242_p3) + unsigned(trunc_ln60_fu_250_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state29 <= ap_CS_fsm(28);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state33 <= ap_CS_fsm(32);
    ap_CS_fsm_state34 <= ap_CS_fsm(33);
    ap_CS_fsm_state35 <= ap_CS_fsm(34);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done)
    begin
        if ((grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done)
    begin
        if ((grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;

    ap_ST_fsm_state35_blk_assign_proc : process(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done)
    begin
        if ((grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state35_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state35_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done)
    begin
        if ((grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state6, icmp_ln52_fu_216_p2)
    begin
        if (((icmp_ln52_fu_216_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, icmp_ln52_fu_216_p2)
    begin
        if (((icmp_ln52_fu_216_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start <= grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg;
    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg;
    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg;
    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start <= grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg;

    grp_fu_162_p0_assign_proc : process(reg_193, conv2_reg_381, ap_CS_fsm_state24, ap_CS_fsm_state29)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
            grp_fu_162_p0 <= reg_193;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            grp_fu_162_p0 <= conv2_reg_381;
        else 
            grp_fu_162_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_162_p1_assign_proc : process(ap_CS_fsm_state24, ap_CS_fsm_state29)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
            grp_fu_162_p1 <= ap_const_lv64_3F80000000000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            grp_fu_162_p1 <= ap_const_lv64_407F400000000000;
        else 
            grp_fu_162_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_167_p0_assign_proc : process(reg_199, conv3_reg_386, ap_CS_fsm_state24, ap_CS_fsm_state29)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
            grp_fu_167_p0 <= reg_199;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            grp_fu_167_p0 <= conv3_reg_386;
        else 
            grp_fu_167_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_167_p1_assign_proc : process(ap_CS_fsm_state24, ap_CS_fsm_state29)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
            grp_fu_167_p1 <= ap_const_lv64_3F80000000000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            grp_fu_167_p1 <= ap_const_lv64_407F400000000000;
        else 
            grp_fu_167_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_174_ce_assign_proc : process(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_ce, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_174_ce <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_ce;
        else 
            grp_fu_174_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_174_p0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din0, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out, ap_CS_fsm_state4, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_174_p0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_174_p0 <= grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out;
        else 
            grp_fu_174_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_174_p1_assign_proc : process(conv1_reg_365, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_174_p1 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_174_p1 <= conv1_reg_365;
        else 
            grp_fu_174_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_186_ce_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state23, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_ce, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state20, ap_CS_fsm_state9, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_186_ce <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_ce;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or ((grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            grp_fu_186_ce <= ap_const_logic_1;
        else 
            grp_fu_186_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_186_p0_assign_proc : process(pseudoimage_count_q0, x_reg_332, ap_CS_fsm_state8, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_186_p0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_186_p0 <= x_reg_332;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_186_p0 <= pseudoimage_count_q0;
        else 
            grp_fu_186_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_406_ce_assign_proc : process(ap_CS_fsm_state11, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_ce, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_ce, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            grp_fu_406_ce <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_406_ce <= grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_ce;
        else 
            grp_fu_406_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_406_opcode_assign_proc : process(ap_CS_fsm_state11, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_opcode, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_opcode, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            grp_fu_406_opcode <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_opcode),2));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_406_opcode <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_opcode),2));
        else 
            grp_fu_406_opcode <= "XX";
        end if; 
    end process;


    grp_fu_406_p0_assign_proc : process(ap_CS_fsm_state11, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din0, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din0, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            grp_fu_406_p0 <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_406_p0 <= grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din0;
        else 
            grp_fu_406_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_406_p1_assign_proc : process(ap_CS_fsm_state11, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din1, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din1, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            grp_fu_406_p1 <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_406_p1 <= grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din1;
        else 
            grp_fu_406_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln52_fu_216_p2 <= "1" when (i_1_fu_52 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out) else "0";

    indices_address0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_address0, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, zext_ln52_fu_227_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            indices_address0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            indices_address0 <= grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_address0;
        else 
            indices_address0 <= zext_ln52_fu_227_p1(10 - 1 downto 0);
        end if; 
    end process;


    indices_ce0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_ce0, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, indices_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            indices_ce0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            indices_ce0 <= grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_ce0;
        else 
            indices_ce0 <= indices_ce0_local;
        end if; 
    end process;


    indices_ce0_local_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            indices_ce0_local <= ap_const_logic_1;
        else 
            indices_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    indices_d0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_d0, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            indices_d0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            indices_d0 <= grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_d0;
        else 
            indices_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    indices_first_address0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_address0, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, zext_ln52_fu_227_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            indices_first_address0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            indices_first_address0 <= grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_address0;
        else 
            indices_first_address0 <= zext_ln52_fu_227_p1(10 - 1 downto 0);
        end if; 
    end process;


    indices_first_ce0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_ce0, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, indices_first_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            indices_first_ce0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            indices_first_ce0 <= grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_ce0;
        else 
            indices_first_ce0 <= indices_first_ce0_local;
        end if; 
    end process;


    indices_first_ce0_local_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            indices_first_ce0_local <= ap_const_logic_1;
        else 
            indices_first_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    indices_first_d0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_d0, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            indices_first_d0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            indices_first_d0 <= grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_d0;
        else 
            indices_first_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    indices_first_we0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_we0, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            indices_first_we0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            indices_first_we0 <= grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_we0;
        else 
            indices_first_we0 <= ap_const_logic_0;
        end if; 
    end process;


    indices_we0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_we0, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            indices_we0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            indices_we0 <= grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_we0;
        else 
            indices_we0 <= ap_const_logic_0;
        end if; 
    end process;

    pointcloud_address0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_address0;
    pointcloud_ce0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_ce0;

    pseudoimage_count_address0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_address0, ap_CS_fsm_state4, zext_ln60_fu_260_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pseudoimage_count_address0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_address0;
        else 
            pseudoimage_count_address0 <= zext_ln60_fu_260_p1(14 - 1 downto 0);
        end if; 
    end process;


    pseudoimage_count_ce0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_ce0, ap_CS_fsm_state4, pseudoimage_count_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pseudoimage_count_ce0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_ce0;
        else 
            pseudoimage_count_ce0 <= pseudoimage_count_ce0_local;
        end if; 
    end process;


    pseudoimage_count_ce0_local_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            pseudoimage_count_ce0_local <= ap_const_logic_1;
        else 
            pseudoimage_count_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pseudoimage_count_d0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_d0;

    pseudoimage_count_we0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pseudoimage_count_we0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_we0;
        else 
            pseudoimage_count_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pseudoimage_data_address0_assign_proc : process(ap_CS_fsm_state11, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_address0, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_address0, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address0, ap_CS_fsm_state4, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            pseudoimage_data_address0 <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            pseudoimage_data_address0 <= grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pseudoimage_data_address0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_address0;
        else 
            pseudoimage_data_address0 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    pseudoimage_data_address1 <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address1;

    pseudoimage_data_ce0_assign_proc : process(ap_CS_fsm_state11, grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_ce0, grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_ce0, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce0, ap_CS_fsm_state4, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            pseudoimage_data_ce0 <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            pseudoimage_data_ce0 <= grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pseudoimage_data_ce0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_ce0;
        else 
            pseudoimage_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pseudoimage_data_ce1_assign_proc : process(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce1, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            pseudoimage_data_ce1 <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce1;
        else 
            pseudoimage_data_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    pseudoimage_data_d0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_d0, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_d0, ap_CS_fsm_state4, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            pseudoimage_data_d0 <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pseudoimage_data_d0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_d0;
        else 
            pseudoimage_data_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    pseudoimage_data_we0_assign_proc : process(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_we0, grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_we0, ap_CS_fsm_state4, ap_CS_fsm_state35)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            pseudoimage_data_we0 <= grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pseudoimage_data_we0 <= grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_we0;
        else 
            pseudoimage_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_265_p3 <= (add_ln60_reg_342 & ap_const_lv6_0);
    tmp_s_fu_242_p3 <= (trunc_ln53_fu_238_p1 & ap_const_lv7_0);
    trunc_ln53_fu_238_p1 <= indices_q0(7 - 1 downto 0);
    trunc_ln60_fu_250_p1 <= indices_first_q0(14 - 1 downto 0);
    zext_ln52_fu_227_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_fu_52),64));
    zext_ln60_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln60_fu_254_p2),64));
end behav;
