-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculate_pseudoimage_calculate_pseudoimage_Pipeline_collection_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pointcloud_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pointcloud_ce0 : OUT STD_LOGIC;
    pointcloud_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    pseudoimage_count_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    pseudoimage_count_ce0 : OUT STD_LOGIC;
    pseudoimage_count_we0 : OUT STD_LOGIC;
    pseudoimage_count_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    pseudoimage_count_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    pseudoimage_data_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    pseudoimage_data_ce0 : OUT STD_LOGIC;
    pseudoimage_data_we0 : OUT STD_LOGIC;
    pseudoimage_data_d0 : OUT STD_LOGIC_VECTOR (575 downto 0);
    pseudoimage_data_q0 : IN STD_LOGIC_VECTOR (575 downto 0);
    indices_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    indices_ce0 : OUT STD_LOGIC;
    indices_we0 : OUT STD_LOGIC;
    indices_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    indices_first_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    indices_first_ce0 : OUT STD_LOGIC;
    indices_first_we0 : OUT STD_LOGIC;
    indices_first_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    pillar_count_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    pillar_count_out_ap_vld : OUT STD_LOGIC;
    grp_fu_174_p_din0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_174_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_174_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_174_p_ce : OUT STD_LOGIC;
    grp_fu_186_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_186_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_186_p_ce : OUT STD_LOGIC );
end;


architecture behav of calculate_pseudoimage_calculate_pseudoimage_Pipeline_collection_loop is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv64_407F400000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0100000001111111010000000000000000000000000000000000000000000000";
    constant ap_const_lv10_3E8 : STD_LOGIC_VECTOR (9 downto 0) := "1111101000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_73 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_23F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln32_reg_844 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln32_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_844_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln32_fu_229_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter12_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter13_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter14_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_848_pp0_iter15_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal pointcloud_load_reg_859 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal pointcloud_load_reg_859_pp0_iter1_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter2_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter3_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter4_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter5_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter6_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter7_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter8_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter9_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter10_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter11_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter12_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter13_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter14_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal pointcloud_load_reg_859_pp0_iter15_reg : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln71_1_fu_343_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal select_ln71_1_reg_864 : STD_LOGIC_VECTOR (24 downto 0);
    signal select_ln71_5_fu_461_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal select_ln71_5_reg_869 : STD_LOGIC_VECTOR (24 downto 0);
    signal and_ln_fu_469_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln1_fu_477_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv4_reg_884 : STD_LOGIC_VECTOR (63 downto 0);
    signal conv_reg_889 : STD_LOGIC_VECTOR (63 downto 0);
    signal xs_exp_1_reg_894 : STD_LOGIC_VECTOR (10 downto 0);
    signal xs_exp_1_reg_894_pp0_iter14_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln505_1_fu_497_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln505_1_reg_900 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln505_1_reg_900_pp0_iter14_reg : STD_LOGIC_VECTOR (51 downto 0);
    signal xs_exp_3_reg_905 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln505_2_fu_513_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln505_2_reg_911 : STD_LOGIC_VECTOR (51 downto 0);
    signal val_fu_604_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_916 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_1_fu_703_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_1_reg_921 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_fu_723_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln36_reg_926 : STD_LOGIC_VECTOR (13 downto 0);
    signal pseudoimage_count_addr_reg_931 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln37_fu_755_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_936 : STD_LOGIC_VECTOR (0 downto 0);
    signal pseudoimage_data_addr_reg_943 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln36_fu_729_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln38_fu_761_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln43_fu_791_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_116 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln32_fu_223_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal pillar_count_fu_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pillar_count_1_fu_770_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter15_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to14 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal pointcloud_ce0_local : STD_LOGIC;
    signal pseudoimage_count_ce0_local : STD_LOGIC;
    signal pseudoimage_count_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal pseudoimage_count_we0_local : STD_LOGIC;
    signal zext_ln48_fu_802_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal indices_we0_local : STD_LOGIC;
    signal indices_ce0_local : STD_LOGIC;
    signal indices_first_we0_local : STD_LOGIC;
    signal indices_first_ce0_local : STD_LOGIC;
    signal pseudoimage_data_ce0_local : STD_LOGIC;
    signal pseudoimage_data_address0_local : STD_LOGIC_VECTOR (19 downto 0);
    signal pseudoimage_data_we0_local : STD_LOGIC;
    signal or_ln46_3_fu_817_p3 : STD_LOGIC_VECTOR (575 downto 0);
    signal grp_fu_196_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_201_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln505_fu_249_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal mantissa_fu_253_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal xs_exp_fu_239_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln486_fu_267_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln486_fu_271_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln71_fu_285_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_9_fu_277_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln71_fu_291_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln71_fu_295_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln71_1_fu_303_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_fu_263_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln71_fu_307_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal lshr_ln71_fu_311_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal shl_ln71_fu_317_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_fu_323_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_1_fu_333_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_i1_fu_361_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal mantissa_2_fu_371_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal xs_exp_2_fu_351_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln486_2_fu_385_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln486_2_fu_389_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln71_2_fu_403_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_11_fu_395_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln71_4_fu_409_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln71_4_fu_413_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln71_5_fu_421_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_2_fu_381_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln71_2_fu_425_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal lshr_ln71_2_fu_429_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal shl_ln71_2_fu_435_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_4_fu_441_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_5_fu_451_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal data_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_1_fu_501_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal mantissa_1_fu_517_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln486_1_fu_530_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln486_1_fu_533_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln71_1_fu_547_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_539_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln71_2_fu_552_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln71_2_fu_556_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln71_3_fu_564_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_1_fu_526_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln71_1_fu_568_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal lshr_ln71_1_fu_572_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal shl_ln71_1_fu_578_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_2_fu_584_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_594_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal mantissa_3_fu_616_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln486_3_fu_629_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln486_3_fu_632_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln71_3_fu_646_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_12_fu_638_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln71_6_fu_651_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln71_6_fu_655_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln71_7_fu_663_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_3_fu_625_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln71_3_fu_667_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal lshr_ln71_3_fu_671_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal shl_ln71_3_fu_677_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_6_fu_683_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_693_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln74_fu_612_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_8_fu_711_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln36_fu_719_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_15_fu_745_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_13_fu_734_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln43_fu_781_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln43_fu_785_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln36_1_fu_741_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln48_fu_796_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_fu_807_p4 : STD_LOGIC_VECTOR (319 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calculate_pseudoimage_ddiv_64ns_64ns_64_22_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculate_pseudoimage_uitodp_32ns_64_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculate_pseudoimage_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component calculate_pseudoimage_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter15_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter10_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter10_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter11_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter11_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter12_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter12_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter13_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter13_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter14_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter14_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter15_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter15_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter6_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter7_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter8_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter9_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then 
                ap_loop_exit_ready_pp0_iter9_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
            end if; 
        end if;
    end process;

    i_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln32_fu_217_p2 = ap_const_lv1_0))) then 
                    i_fu_116 <= add_ln32_fu_223_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_116 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    pillar_count_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                pillar_count_fu_120 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln38_fu_761_p2 = ap_const_lv1_1) and (icmp_ln37_fu_755_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                pillar_count_fu_120 <= pillar_count_1_fu_770_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln36_reg_926 <= add_ln36_fu_723_p2;
                icmp_ln32_reg_844 <= icmp_ln32_fu_217_p2;
                icmp_ln32_reg_844_pp0_iter10_reg <= icmp_ln32_reg_844_pp0_iter9_reg;
                icmp_ln32_reg_844_pp0_iter11_reg <= icmp_ln32_reg_844_pp0_iter10_reg;
                icmp_ln32_reg_844_pp0_iter12_reg <= icmp_ln32_reg_844_pp0_iter11_reg;
                icmp_ln32_reg_844_pp0_iter13_reg <= icmp_ln32_reg_844_pp0_iter12_reg;
                icmp_ln32_reg_844_pp0_iter14_reg <= icmp_ln32_reg_844_pp0_iter13_reg;
                icmp_ln32_reg_844_pp0_iter1_reg <= icmp_ln32_reg_844;
                icmp_ln32_reg_844_pp0_iter2_reg <= icmp_ln32_reg_844_pp0_iter1_reg;
                icmp_ln32_reg_844_pp0_iter3_reg <= icmp_ln32_reg_844_pp0_iter2_reg;
                icmp_ln32_reg_844_pp0_iter4_reg <= icmp_ln32_reg_844_pp0_iter3_reg;
                icmp_ln32_reg_844_pp0_iter5_reg <= icmp_ln32_reg_844_pp0_iter4_reg;
                icmp_ln32_reg_844_pp0_iter6_reg <= icmp_ln32_reg_844_pp0_iter5_reg;
                icmp_ln32_reg_844_pp0_iter7_reg <= icmp_ln32_reg_844_pp0_iter6_reg;
                icmp_ln32_reg_844_pp0_iter8_reg <= icmp_ln32_reg_844_pp0_iter7_reg;
                icmp_ln32_reg_844_pp0_iter9_reg <= icmp_ln32_reg_844_pp0_iter8_reg;
                pseudoimage_count_addr_reg_931 <= zext_ln36_fu_729_p1(14 - 1 downto 0);
                trunc_ln505_2_reg_911 <= trunc_ln505_2_fu_513_p1;
                val_1_reg_921 <= val_1_fu_703_p3;
                val_reg_916 <= val_fu_604_p3;
                xs_exp_3_reg_905 <= data_1_fu_501_p1(62 downto 52);
                    zext_ln32_reg_848(9 downto 0) <= zext_ln32_fu_229_p1(9 downto 0);
                    zext_ln32_reg_848_pp0_iter10_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter9_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter11_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter10_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter12_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter11_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter13_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter12_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter14_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter13_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter15_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter14_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter1_reg(9 downto 0) <= zext_ln32_reg_848(9 downto 0);
                    zext_ln32_reg_848_pp0_iter2_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter1_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter3_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter2_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter4_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter3_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter5_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter4_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter6_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter5_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter7_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter6_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter8_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter7_reg(9 downto 0);
                    zext_ln32_reg_848_pp0_iter9_reg(9 downto 0) <= zext_ln32_reg_848_pp0_iter8_reg(9 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                conv4_reg_884 <= grp_fu_186_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                conv_reg_889 <= grp_fu_186_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln37_reg_936 <= icmp_ln37_fu_755_p2;
                pointcloud_load_reg_859 <= pointcloud_q0;
                pointcloud_load_reg_859_pp0_iter10_reg <= pointcloud_load_reg_859_pp0_iter9_reg;
                pointcloud_load_reg_859_pp0_iter11_reg <= pointcloud_load_reg_859_pp0_iter10_reg;
                pointcloud_load_reg_859_pp0_iter12_reg <= pointcloud_load_reg_859_pp0_iter11_reg;
                pointcloud_load_reg_859_pp0_iter13_reg <= pointcloud_load_reg_859_pp0_iter12_reg;
                pointcloud_load_reg_859_pp0_iter14_reg <= pointcloud_load_reg_859_pp0_iter13_reg;
                pointcloud_load_reg_859_pp0_iter15_reg <= pointcloud_load_reg_859_pp0_iter14_reg;
                pointcloud_load_reg_859_pp0_iter1_reg <= pointcloud_load_reg_859;
                pointcloud_load_reg_859_pp0_iter2_reg <= pointcloud_load_reg_859_pp0_iter1_reg;
                pointcloud_load_reg_859_pp0_iter3_reg <= pointcloud_load_reg_859_pp0_iter2_reg;
                pointcloud_load_reg_859_pp0_iter4_reg <= pointcloud_load_reg_859_pp0_iter3_reg;
                pointcloud_load_reg_859_pp0_iter5_reg <= pointcloud_load_reg_859_pp0_iter4_reg;
                pointcloud_load_reg_859_pp0_iter6_reg <= pointcloud_load_reg_859_pp0_iter5_reg;
                pointcloud_load_reg_859_pp0_iter7_reg <= pointcloud_load_reg_859_pp0_iter6_reg;
                pointcloud_load_reg_859_pp0_iter8_reg <= pointcloud_load_reg_859_pp0_iter7_reg;
                pointcloud_load_reg_859_pp0_iter9_reg <= pointcloud_load_reg_859_pp0_iter8_reg;
                pseudoimage_data_addr_reg_943 <= zext_ln43_fu_791_p1(20 - 1 downto 0);
                select_ln71_1_reg_864 <= select_ln71_1_fu_343_p3;
                select_ln71_5_reg_869 <= select_ln71_5_fu_461_p3;
                trunc_ln505_1_reg_900 <= trunc_ln505_1_fu_497_p1;
                trunc_ln505_1_reg_900_pp0_iter14_reg <= trunc_ln505_1_reg_900;
                xs_exp_1_reg_894 <= data_fu_485_p1(62 downto 52);
                xs_exp_1_reg_894_pp0_iter14_reg <= xs_exp_1_reg_894;
            end if;
        end if;
    end process;
    zext_ln32_reg_848(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter1_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter2_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter3_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter4_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter5_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter6_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter7_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter8_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter9_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter10_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter11_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter12_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter13_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter14_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_848_pp0_iter15_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter15_stage0, ap_idle_pp0_0to14)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to14 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter15_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln32_fu_223_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv10_1));
    add_ln36_fu_723_p2 <= std_logic_vector(unsigned(tmp_8_fu_711_p3) + unsigned(trunc_ln36_fu_719_p1));
    add_ln43_fu_785_p2 <= std_logic_vector(unsigned(tmp_13_fu_734_p3) + unsigned(trunc_ln43_fu_781_p1));
    add_ln486_1_fu_533_p2 <= std_logic_vector(unsigned(zext_ln486_1_fu_530_p1) + unsigned(ap_const_lv12_C01));
    add_ln486_2_fu_389_p2 <= std_logic_vector(unsigned(zext_ln486_2_fu_385_p1) + unsigned(ap_const_lv12_C01));
    add_ln486_3_fu_632_p2 <= std_logic_vector(unsigned(zext_ln486_3_fu_629_p1) + unsigned(ap_const_lv12_C01));
    add_ln486_fu_271_p2 <= std_logic_vector(unsigned(zext_ln486_fu_267_p1) + unsigned(ap_const_lv12_C01));
    add_ln48_fu_796_p2 <= std_logic_vector(unsigned(trunc_ln36_1_fu_741_p1) + unsigned(ap_const_lv7_1));
    and_ln1_fu_477_p3 <= (select_ln71_5_reg_869 & ap_const_lv7_0);
    and_ln_fu_469_p3 <= (select_ln71_1_reg_864 & ap_const_lv7_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln32_reg_844)
    begin
        if (((icmp_ln32_reg_844 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter15_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter15, icmp_ln32_reg_844_pp0_iter14_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln32_reg_844_pp0_iter14_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter15_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter15_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter15_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter15_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to14_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to14 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to14 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_116, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_116;
        end if; 
    end process;

    data_1_fu_501_p1 <= grp_fu_174_p_dout0;
    data_fu_485_p1 <= grp_fu_174_p_dout0;
    grp_fu_174_p_ce <= ap_const_logic_1;
    grp_fu_174_p_din0 <= grp_fu_196_p0;
    grp_fu_174_p_din1 <= ap_const_lv64_407F400000000000;
    grp_fu_186_p_ce <= ap_const_logic_1;
    grp_fu_186_p_din0 <= grp_fu_201_p0;

    grp_fu_196_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, conv4_reg_884, conv_reg_889, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_196_p0 <= conv_reg_889;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_196_p0 <= conv4_reg_884;
            else 
                grp_fu_196_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_196_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_201_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, and_ln_fu_469_p3, and_ln1_fu_477_p3, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_201_p0 <= and_ln1_fu_477_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_201_p0 <= and_ln_fu_469_p3;
            else 
                grp_fu_201_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_201_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln32_fu_217_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv10_3E8) else "0";
    icmp_ln37_fu_755_p2 <= "1" when (tmp_15_fu_745_p4 = ap_const_lv26_0) else "0";
    icmp_ln38_fu_761_p2 <= "1" when (pseudoimage_count_q0 = ap_const_lv32_0) else "0";
    indices_address0 <= zext_ln32_reg_848_pp0_iter15_reg(10 - 1 downto 0);
    indices_ce0 <= indices_ce0_local;

    indices_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            indices_ce0_local <= ap_const_logic_1;
        else 
            indices_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    indices_d0 <= val_reg_916;
    indices_first_address0 <= zext_ln32_reg_848_pp0_iter15_reg(10 - 1 downto 0);
    indices_first_ce0 <= indices_first_ce0_local;

    indices_first_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            indices_first_ce0_local <= ap_const_logic_1;
        else 
            indices_first_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    indices_first_d0 <= val_1_reg_921;
    indices_first_we0 <= indices_first_we0_local;

    indices_first_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln37_fu_755_p2, icmp_ln38_fu_761_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln38_fu_761_p2 = ap_const_lv1_1) and (icmp_ln37_fu_755_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            indices_first_we0_local <= ap_const_logic_1;
        else 
            indices_first_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    indices_we0 <= indices_we0_local;

    indices_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln37_fu_755_p2, icmp_ln38_fu_761_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln38_fu_761_p2 = ap_const_lv1_1) and (icmp_ln37_fu_755_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            indices_we0_local <= ap_const_logic_1;
        else 
            indices_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln71_1_fu_572_p2 <= std_logic_vector(shift_right(unsigned(zext_ln68_1_fu_526_p1),to_integer(unsigned('0' & zext_ln71_1_fu_568_p1(31-1 downto 0)))));
    lshr_ln71_2_fu_429_p2 <= std_logic_vector(shift_right(unsigned(zext_ln68_2_fu_381_p1),to_integer(unsigned('0' & zext_ln71_2_fu_425_p1(31-1 downto 0)))));
    lshr_ln71_3_fu_671_p2 <= std_logic_vector(shift_right(unsigned(zext_ln68_3_fu_625_p1),to_integer(unsigned('0' & zext_ln71_3_fu_667_p1(31-1 downto 0)))));
    lshr_ln71_fu_311_p2 <= std_logic_vector(shift_right(unsigned(zext_ln68_fu_263_p1),to_integer(unsigned('0' & zext_ln71_fu_307_p1(31-1 downto 0)))));
    mantissa_1_fu_517_p4 <= ((ap_const_lv1_1 & trunc_ln505_1_reg_900_pp0_iter14_reg) & ap_const_lv1_0);
    mantissa_2_fu_371_p4 <= ((ap_const_lv1_1 & tmp_i1_fu_361_p4) & ap_const_lv1_0);
    mantissa_3_fu_616_p4 <= ((ap_const_lv1_1 & trunc_ln505_2_reg_911) & ap_const_lv1_0);
    mantissa_fu_253_p4 <= ((ap_const_lv1_1 & trunc_ln505_fu_249_p1) & ap_const_lv1_0);
    or_ln46_3_fu_817_p3 <= (tmp_s_fu_807_p4 & pointcloud_load_reg_859_pp0_iter15_reg);
    pillar_count_1_fu_770_p2 <= std_logic_vector(unsigned(pillar_count_fu_120) + unsigned(ap_const_lv32_1));
    pillar_count_out <= pillar_count_fu_120;

    pillar_count_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_844_pp0_iter14_reg, ap_loop_exit_ready_pp0_iter15_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter15_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln32_reg_844_pp0_iter14_reg = ap_const_lv1_1))) then 
            pillar_count_out_ap_vld <= ap_const_logic_1;
        else 
            pillar_count_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pointcloud_address0 <= zext_ln32_fu_229_p1(10 - 1 downto 0);
    pointcloud_ce0 <= pointcloud_ce0_local;

    pointcloud_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pointcloud_ce0_local <= ap_const_logic_1;
        else 
            pointcloud_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pseudoimage_count_address0 <= pseudoimage_count_address0_local;

    pseudoimage_count_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, pseudoimage_count_addr_reg_931, ap_block_pp0_stage0, zext_ln36_fu_729_p1, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter15 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                pseudoimage_count_address0_local <= pseudoimage_count_addr_reg_931;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                pseudoimage_count_address0_local <= zext_ln36_fu_729_p1(14 - 1 downto 0);
            else 
                pseudoimage_count_address0_local <= "XXXXXXXXXXXXXX";
            end if;
        else 
            pseudoimage_count_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    pseudoimage_count_ce0 <= pseudoimage_count_ce0_local;

    pseudoimage_count_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            pseudoimage_count_ce0_local <= ap_const_logic_1;
        else 
            pseudoimage_count_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pseudoimage_count_d0 <= zext_ln48_fu_802_p1;
    pseudoimage_count_we0 <= pseudoimage_count_we0_local;

    pseudoimage_count_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln37_fu_755_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln37_fu_755_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pseudoimage_count_we0_local <= ap_const_logic_1;
        else 
            pseudoimage_count_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pseudoimage_data_address0 <= pseudoimage_data_address0_local;

    pseudoimage_data_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_CS_fsm_pp0_stage1, pseudoimage_data_addr_reg_943, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln43_fu_791_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pseudoimage_data_address0_local <= pseudoimage_data_addr_reg_943;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pseudoimage_data_address0_local <= zext_ln43_fu_791_p1(20 - 1 downto 0);
        else 
            pseudoimage_data_address0_local <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    pseudoimage_data_ce0 <= pseudoimage_data_ce0_local;

    pseudoimage_data_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            pseudoimage_data_ce0_local <= ap_const_logic_1;
        else 
            pseudoimage_data_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pseudoimage_data_d0 <= or_ln46_3_fu_817_p3;
    pseudoimage_data_we0 <= pseudoimage_data_we0_local;

    pseudoimage_data_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter16, ap_block_pp0_stage0_11001, icmp_ln37_reg_936)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln37_reg_936 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pseudoimage_data_we0_local <= ap_const_logic_1;
        else 
            pseudoimage_data_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln71_1_fu_343_p3 <= 
        tmp_fu_323_p4 when (tmp_9_fu_277_p3(0) = '1') else 
        tmp_1_fu_333_p4;
    select_ln71_2_fu_556_p3 <= 
        sext_ln71_2_fu_552_p1 when (tmp_10_fu_539_p3(0) = '1') else 
        add_ln486_1_fu_533_p2;
    select_ln71_4_fu_413_p3 <= 
        sext_ln71_4_fu_409_p1 when (tmp_11_fu_395_p3(0) = '1') else 
        add_ln486_2_fu_389_p2;
    select_ln71_5_fu_461_p3 <= 
        tmp_4_fu_441_p4 when (tmp_11_fu_395_p3(0) = '1') else 
        tmp_5_fu_451_p4;
    select_ln71_6_fu_655_p3 <= 
        sext_ln71_6_fu_651_p1 when (tmp_12_fu_638_p3(0) = '1') else 
        add_ln486_3_fu_632_p2;
    select_ln71_fu_295_p3 <= 
        sext_ln71_fu_291_p1 when (tmp_9_fu_277_p3(0) = '1') else 
        add_ln486_fu_271_p2;
        sext_ln71_1_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln71_fu_295_p3),32));

        sext_ln71_2_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln71_1_fu_547_p2),12));

        sext_ln71_3_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln71_2_fu_556_p3),32));

        sext_ln71_4_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln71_2_fu_403_p2),12));

        sext_ln71_5_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln71_4_fu_413_p3),32));

        sext_ln71_6_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln71_3_fu_646_p2),12));

        sext_ln71_7_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln71_6_fu_655_p3),32));

        sext_ln71_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln71_fu_285_p2),12));

    shl_ln71_1_fu_578_p2 <= std_logic_vector(shift_left(unsigned(zext_ln68_1_fu_526_p1),to_integer(unsigned('0' & zext_ln71_1_fu_568_p1(31-1 downto 0)))));
    shl_ln71_2_fu_435_p2 <= std_logic_vector(shift_left(unsigned(zext_ln68_2_fu_381_p1),to_integer(unsigned('0' & zext_ln71_2_fu_425_p1(31-1 downto 0)))));
    shl_ln71_3_fu_677_p2 <= std_logic_vector(shift_left(unsigned(zext_ln68_3_fu_625_p1),to_integer(unsigned('0' & zext_ln71_3_fu_667_p1(31-1 downto 0)))));
    shl_ln71_fu_317_p2 <= std_logic_vector(shift_left(unsigned(zext_ln68_fu_263_p1),to_integer(unsigned('0' & zext_ln71_fu_307_p1(31-1 downto 0)))));
    sub_ln71_1_fu_547_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(xs_exp_1_reg_894_pp0_iter14_reg));
    sub_ln71_2_fu_403_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(xs_exp_2_fu_351_p4));
    sub_ln71_3_fu_646_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(xs_exp_3_reg_905));
    sub_ln71_fu_285_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(xs_exp_fu_239_p4));
    tmp_10_fu_539_p3 <= add_ln486_1_fu_533_p2(11 downto 11);
    tmp_11_fu_395_p3 <= add_ln486_2_fu_389_p2(11 downto 11);
    tmp_12_fu_638_p3 <= add_ln486_3_fu_632_p2(11 downto 11);
    tmp_13_fu_734_p3 <= (add_ln36_reg_926 & ap_const_lv6_0);
    tmp_15_fu_745_p4 <= pseudoimage_count_q0(31 downto 6);
    tmp_1_fu_333_p4 <= shl_ln71_fu_317_p2(77 downto 53);
    tmp_2_fu_584_p4 <= lshr_ln71_1_fu_572_p2(84 downto 53);
    tmp_3_fu_594_p4 <= shl_ln71_1_fu_578_p2(84 downto 53);
    tmp_4_fu_441_p4 <= lshr_ln71_2_fu_429_p2(77 downto 53);
    tmp_5_fu_451_p4 <= shl_ln71_2_fu_435_p2(77 downto 53);
    tmp_6_fu_683_p4 <= lshr_ln71_3_fu_671_p2(84 downto 53);
    tmp_7_fu_693_p4 <= shl_ln71_3_fu_677_p2(84 downto 53);
    tmp_8_fu_711_p3 <= (trunc_ln74_fu_612_p1 & ap_const_lv7_0);
    tmp_9_fu_277_p3 <= add_ln486_fu_271_p2(11 downto 11);
    tmp_fu_323_p4 <= lshr_ln71_fu_311_p2(77 downto 53);
    tmp_i1_fu_361_p4 <= pointcloud_q0(115 downto 64);
    tmp_s_fu_807_p4 <= pseudoimage_data_q0(575 downto 256);
    trunc_ln36_1_fu_741_p1 <= pseudoimage_count_q0(7 - 1 downto 0);
    trunc_ln36_fu_719_p1 <= val_1_fu_703_p3(14 - 1 downto 0);
    trunc_ln43_fu_781_p1 <= pseudoimage_count_q0(20 - 1 downto 0);
    trunc_ln505_1_fu_497_p1 <= data_fu_485_p1(52 - 1 downto 0);
    trunc_ln505_2_fu_513_p1 <= data_1_fu_501_p1(52 - 1 downto 0);
    trunc_ln505_fu_249_p1 <= pointcloud_q0(52 - 1 downto 0);
    trunc_ln74_fu_612_p1 <= val_fu_604_p3(7 - 1 downto 0);
    val_1_fu_703_p3 <= 
        tmp_6_fu_683_p4 when (tmp_12_fu_638_p3(0) = '1') else 
        tmp_7_fu_693_p4;
    val_fu_604_p3 <= 
        tmp_2_fu_584_p4 when (tmp_10_fu_539_p3(0) = '1') else 
        tmp_3_fu_594_p4;
    xs_exp_2_fu_351_p4 <= pointcloud_q0(126 downto 116);
    xs_exp_fu_239_p4 <= pointcloud_q0(62 downto 52);
    zext_ln32_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
    zext_ln36_fu_729_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln36_fu_723_p2),64));
    zext_ln43_fu_791_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_fu_785_p2),64));
    zext_ln486_1_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_1_reg_894_pp0_iter14_reg),12));
    zext_ln486_2_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_2_fu_351_p4),12));
    zext_ln486_3_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_3_reg_905),12));
    zext_ln486_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_239_p4),12));
    zext_ln48_fu_802_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln48_fu_796_p2),32));
    zext_ln68_1_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_1_fu_517_p4),137));
    zext_ln68_2_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_2_fu_371_p4),137));
    zext_ln68_3_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_3_fu_616_p4),137));
    zext_ln68_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_253_p4),137));
    zext_ln71_1_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln71_3_fu_564_p1),137));
    zext_ln71_2_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln71_5_fu_421_p1),137));
    zext_ln71_3_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln71_7_fu_663_p1),137));
    zext_ln71_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln71_1_fu_303_p1),137));
end behav;
