-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
Library ieee;
use ieee.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pointpillars_cnn_ctlz_16_16_1_1 is
generic (
    din_WIDTH : INTEGER := 1;
    dout_WIDTH : INTEGER := 1);
port(

    din: in std_logic_vector(din_WIDTH - 1 downto 0);
    dout: out std_logic_vector(dout_WIDTH - 1 downto 0));
end entity;

architecture arch of pointpillars_cnn_ctlz_16_16_1_1 is
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of arch: architecture is "yes";
    signal dout_tmp : std_logic_vector(dout_WIDTH - 1 downto 0);

begin

    dout <=  dout_tmp;


    
    process (din)
    begin 
        dout_tmp <= std_logic_vector(to_unsigned(16, dout_WIDTH));
        for i in 0 to 15 loop
            if din(15 - i) = '1' then
                dout_tmp <= std_logic_vector(to_unsigned(i, dout_WIDTH));
                exit;
            end if;
        end loop;
    end process;



end architecture;
