// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calculate_pseudoimage_calculate_pseudoimage,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku025-ffva1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.139641,HLS_SYN_LAT=2002,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=80,HLS_SYN_LUT=48245,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module calculate_pseudoimage (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pointcloud_address0,
        pointcloud_ce0,
        pointcloud_q0,
        pseudoimage_address0,
        pseudoimage_ce0,
        pseudoimage_we0,
        pseudoimage_d0,
        pseudoimage_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] pointcloud_address0;
output   pointcloud_ce0;
input  [31:0] pointcloud_q0;
output  [13:0] pseudoimage_address0;
output   pseudoimage_ce0;
output   pseudoimage_we0;
output  [2055:0] pseudoimage_d0;
input  [2055:0] pseudoimage_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln19_reg_648;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage1_pp0_iter1_reg;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg    ap_loop_exit_ready_delayed;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln19_fu_177_p2;
reg   [31:0] pointcloud_load_reg_652;
wire   [7:0] x_fu_188_p1;
reg   [7:0] x_reg_658;
wire   [7:0] y_fu_196_p4;
reg   [7:0] y_reg_663;
reg   [13:0] pseudoimage_addr_reg_668;
wire   [63:0] zext_ln19_fu_166_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln23_1_fu_224_p1;
wire    ap_block_pp0_stage1;
reg   [9:0] i_fu_128;
wire   [9:0] i_3_fu_171_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_1;
reg    pointcloud_ce0_local;
reg    pseudoimage_ce0_local;
reg   [13:0] pseudoimage_address0_local;
reg    pseudoimage_we0_local;
wire   [0:0] icmp_ln24_fu_243_p2;
wire   [2055:0] or_ln26_4_fu_627_p3;
wire   [6:0] trunc_ln20_1_fu_192_p1;
wire   [13:0] tmp_8_fu_206_p3;
wire   [13:0] zext_ln23_fu_214_p1;
wire   [13:0] add_ln23_fu_218_p2;
wire   [1:0] tmp_fu_233_p4;
wire   [5:0] trunc_ln25_fu_267_p1;
wire   [10:0] shl_ln_fu_271_p3;
wire   [10:0] or_ln1_fu_283_p3;
wire   [2031:0] zext_ln25_1_fu_291_p1;
wire   [2031:0] shl_ln25_fu_295_p2;
wire   [2031:0] zext_ln25_3_fu_305_p1;
wire   [10:0] or_ln25_1_fu_314_p3;
wire   [2039:0] zext_ln25_4_fu_322_p1;
wire   [2039:0] shl_ln25_2_fu_326_p2;
wire   [2039:0] zext_ln25_6_fu_336_p1;
wire   [10:0] or_ln25_2_fu_345_p3;
wire   [2047:0] zext_ln25_9_fu_353_p1;
wire   [2047:0] shl_ln25_4_fu_357_p2;
wire   [7:0] lshr_ln_fu_249_p4;
wire   [2047:0] zext_ln25_11_fu_367_p1;
wire   [11:0] zext_ln25_fu_279_p1;
wire   [11:0] add_ln25_fu_377_p2;
wire   [2055:0] zext_ln25_7_fu_383_p1;
wire   [7:0] lshr_ln25_1_fu_258_p4;
wire   [2055:0] zext_ln25_8_fu_393_p1;
wire   [7:0] c_fu_229_p1;
wire   [2032:0] zext_ln25_2_fu_301_p1;
wire  signed [2032:0] xor_ln26_fu_409_p2;
wire  signed [2055:0] sext_ln26_fu_415_p1;
wire   [2031:0] trunc_ln26_1_fu_423_p1;
wire   [2031:0] trunc_ln26_fu_419_p1;
wire   [2031:0] and_ln26_4_fu_433_p2;
wire   [2031:0] shl_ln25_1_fu_308_p2;
wire   [2055:0] and_ln26_fu_427_p2;
wire   [23:0] tmp_1_fu_445_p4;
wire   [2031:0] or_ln26_5_fu_439_p2;
wire   [2040:0] zext_ln25_5_fu_332_p1;
wire  signed [2040:0] xor_ln26_1_fu_473_p2;
wire   [7:0] tmp_2_fu_455_p4;
wire   [2055:0] or_ln_fu_465_p3;
wire  signed [2055:0] sext_ln26_1_fu_479_p1;
wire   [2039:0] tmp_3_fu_487_p3;
wire   [2039:0] trunc_ln26_2_fu_483_p1;
wire   [2039:0] and_ln26_5_fu_501_p2;
wire   [2039:0] shl_ln25_3_fu_339_p2;
wire   [2055:0] and_ln26_1_fu_495_p2;
wire   [15:0] tmp_4_fu_513_p4;
wire   [2039:0] or_ln26_fu_507_p2;
wire   [2048:0] zext_ln25_10_fu_363_p1;
wire  signed [2048:0] xor_ln26_2_fu_541_p2;
wire   [7:0] tmp_5_fu_523_p4;
wire   [2055:0] or_ln26_1_fu_533_p3;
wire  signed [2055:0] sext_ln26_2_fu_547_p1;
wire   [2047:0] tmp_6_fu_555_p3;
wire   [2047:0] trunc_ln26_3_fu_551_p1;
wire   [2047:0] and_ln26_6_fu_569_p2;
wire   [2047:0] shl_ln25_5_fu_371_p2;
wire   [2055:0] and_ln26_2_fu_563_p2;
wire   [7:0] tmp_7_fu_581_p4;
wire   [2047:0] or_ln26_6_fu_575_p2;
wire   [2055:0] shl_ln25_6_fu_387_p2;
wire   [2055:0] or_ln26_2_fu_591_p3;
wire   [2055:0] xor_ln26_3_fu_599_p2;
wire   [2055:0] and_ln26_3_fu_605_p2;
wire   [2055:0] shl_ln25_7_fu_397_p2;
wire   [2055:0] or_ln26_3_fu_611_p2;
wire   [2047:0] tmp_s_fu_617_p4;
wire   [7:0] add_ln26_fu_403_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_120;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_128 = 10'd0;
#0 ap_done_reg = 1'b0;
end

calculate_pseudoimage_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
        ap_condition_exit_pp0_iter0_stage1_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0)) | ((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_120)) begin
        i_fu_128 <= i_3_fu_171_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln19_reg_648 <= icmp_ln19_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pointcloud_load_reg_652 <= pointcloud_q0;
        pseudoimage_addr_reg_668 <= zext_ln23_1_fu_224_p1;
        x_reg_658 <= x_fu_188_p1;
        y_reg_663 <= {{pointcloud_q0[15:8]}};
    end
end

always @ (*) begin
    if (((icmp_ln19_reg_648 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln19_reg_648 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_exit_pp0_iter0_stage1_pp0_iter1_reg) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pointcloud_ce0_local = 1'b1;
    end else begin
        pointcloud_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pseudoimage_address0_local = pseudoimage_addr_reg_668;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pseudoimage_address0_local = zext_ln23_1_fu_224_p1;
    end else begin
        pseudoimage_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        pseudoimage_ce0_local = 1'b1;
    end else begin
        pseudoimage_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln24_fu_243_p2 == 1'd1))) begin
        pseudoimage_we0_local = 1'b1;
    end else begin
        pseudoimage_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln23_fu_218_p2 = (tmp_8_fu_206_p3 + zext_ln23_fu_214_p1);

assign add_ln25_fu_377_p2 = (zext_ln25_fu_279_p1 + 12'd32);

assign add_ln26_fu_403_p2 = (c_fu_229_p1 + 8'd1);

assign and_ln26_1_fu_495_p2 = (sext_ln26_1_fu_479_p1 & or_ln_fu_465_p3);

assign and_ln26_2_fu_563_p2 = (sext_ln26_2_fu_547_p1 & or_ln26_1_fu_533_p3);

assign and_ln26_3_fu_605_p2 = (xor_ln26_3_fu_599_p2 & or_ln26_2_fu_591_p3);

assign and_ln26_4_fu_433_p2 = (trunc_ln26_fu_419_p1 & trunc_ln26_1_fu_423_p1);

assign and_ln26_5_fu_501_p2 = (trunc_ln26_2_fu_483_p1 & tmp_3_fu_487_p3);

assign and_ln26_6_fu_569_p2 = (trunc_ln26_3_fu_551_p1 & tmp_6_fu_555_p3);

assign and_ln26_fu_427_p2 = (sext_ln26_fu_415_p1 & pseudoimage_q0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_120 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign c_fu_229_p1 = pseudoimage_q0[7:0];

assign i_3_fu_171_p2 = (ap_sig_allocacmp_i_1 + 10'd1);

assign icmp_ln19_fu_177_p2 = ((ap_sig_allocacmp_i_1 == 10'd999) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_243_p2 = ((tmp_fu_233_p4 == 2'd0) ? 1'b1 : 1'b0);

assign lshr_ln25_1_fu_258_p4 = {{pointcloud_load_reg_652[31:24]}};

assign lshr_ln_fu_249_p4 = {{pointcloud_load_reg_652[23:16]}};

assign or_ln1_fu_283_p3 = {{trunc_ln25_fu_267_p1}, {5'd8}};

assign or_ln25_1_fu_314_p3 = {{trunc_ln25_fu_267_p1}, {5'd16}};

assign or_ln25_2_fu_345_p3 = {{trunc_ln25_fu_267_p1}, {5'd24}};

assign or_ln26_1_fu_533_p3 = {{tmp_4_fu_513_p4}, {or_ln26_fu_507_p2}};

assign or_ln26_2_fu_591_p3 = {{tmp_7_fu_581_p4}, {or_ln26_6_fu_575_p2}};

assign or_ln26_3_fu_611_p2 = (shl_ln25_7_fu_397_p2 | and_ln26_3_fu_605_p2);

assign or_ln26_4_fu_627_p3 = {{tmp_s_fu_617_p4}, {add_ln26_fu_403_p2}};

assign or_ln26_5_fu_439_p2 = (shl_ln25_1_fu_308_p2 | and_ln26_4_fu_433_p2);

assign or_ln26_6_fu_575_p2 = (shl_ln25_5_fu_371_p2 | and_ln26_6_fu_569_p2);

assign or_ln26_fu_507_p2 = (shl_ln25_3_fu_339_p2 | and_ln26_5_fu_501_p2);

assign or_ln_fu_465_p3 = {{tmp_1_fu_445_p4}, {or_ln26_5_fu_439_p2}};

assign pointcloud_address0 = zext_ln19_fu_166_p1;

assign pointcloud_ce0 = pointcloud_ce0_local;

assign pseudoimage_address0 = pseudoimage_address0_local;

assign pseudoimage_ce0 = pseudoimage_ce0_local;

assign pseudoimage_d0 = or_ln26_4_fu_627_p3;

assign pseudoimage_we0 = pseudoimage_we0_local;

assign sext_ln26_1_fu_479_p1 = xor_ln26_1_fu_473_p2;

assign sext_ln26_2_fu_547_p1 = xor_ln26_2_fu_541_p2;

assign sext_ln26_fu_415_p1 = xor_ln26_fu_409_p2;

assign shl_ln25_1_fu_308_p2 = zext_ln25_3_fu_305_p1 << zext_ln25_1_fu_291_p1;

assign shl_ln25_2_fu_326_p2 = 2040'd255 << zext_ln25_4_fu_322_p1;

assign shl_ln25_3_fu_339_p2 = zext_ln25_6_fu_336_p1 << zext_ln25_4_fu_322_p1;

assign shl_ln25_4_fu_357_p2 = 2048'd255 << zext_ln25_9_fu_353_p1;

assign shl_ln25_5_fu_371_p2 = zext_ln25_11_fu_367_p1 << zext_ln25_9_fu_353_p1;

assign shl_ln25_6_fu_387_p2 = 2056'd255 << zext_ln25_7_fu_383_p1;

assign shl_ln25_7_fu_397_p2 = zext_ln25_8_fu_393_p1 << zext_ln25_7_fu_383_p1;

assign shl_ln25_fu_295_p2 = 2032'd255 << zext_ln25_1_fu_291_p1;

assign shl_ln_fu_271_p3 = {{trunc_ln25_fu_267_p1}, {5'd0}};

assign tmp_1_fu_445_p4 = {{and_ln26_fu_427_p2[2055:2032]}};

assign tmp_2_fu_455_p4 = {{and_ln26_fu_427_p2[2039:2032]}};

assign tmp_3_fu_487_p3 = {{tmp_2_fu_455_p4}, {or_ln26_5_fu_439_p2}};

assign tmp_4_fu_513_p4 = {{and_ln26_1_fu_495_p2[2055:2040]}};

assign tmp_5_fu_523_p4 = {{and_ln26_1_fu_495_p2[2047:2040]}};

assign tmp_6_fu_555_p3 = {{tmp_5_fu_523_p4}, {or_ln26_fu_507_p2}};

assign tmp_7_fu_581_p4 = {{and_ln26_2_fu_563_p2[2055:2048]}};

assign tmp_8_fu_206_p3 = {{trunc_ln20_1_fu_192_p1}, {7'd0}};

assign tmp_fu_233_p4 = {{pseudoimage_q0[7:6]}};

assign tmp_s_fu_617_p4 = {{or_ln26_3_fu_611_p2[2055:8]}};

assign trunc_ln20_1_fu_192_p1 = pointcloud_q0[6:0];

assign trunc_ln25_fu_267_p1 = pseudoimage_q0[5:0];

assign trunc_ln26_1_fu_423_p1 = pseudoimage_q0[2031:0];

assign trunc_ln26_2_fu_483_p1 = xor_ln26_1_fu_473_p2[2039:0];

assign trunc_ln26_3_fu_551_p1 = xor_ln26_2_fu_541_p2[2047:0];

assign trunc_ln26_fu_419_p1 = xor_ln26_fu_409_p2[2031:0];

assign x_fu_188_p1 = pointcloud_q0[7:0];

assign xor_ln26_1_fu_473_p2 = (zext_ln25_5_fu_332_p1 ^ 2041'd252476609932117244536834974130233999690969552107152219001018323652536368272405397603103136027522761435068109069702328277297809055863210321055376190519127211879928729432039031966798419924919157084344200299875527877162439208145466845014360112019345081801419108219033633147559186652664576629746503118155706136889955729606783925161601365520035699178563875275986891078732856713523642130534846204298895256751383724421434404050483260606237118377356608628153887603385056493961919411803282888477789857241650964606863613911380452617546853659007801861058790362417479183934391683072106286291550614101188657762155106336403095551);

assign xor_ln26_2_fu_541_p2 = (zext_ln25_10_fu_363_p1 ^ 2049'd64634012142622014601429753377339903920888205339430968064260690855049310277735781786394402823045826927377435921843796038988239118300981842190176304772896566241261754734601992183500395500779304213592115276768135136553584437285239512323676188676952340941163291704072610085775151783082131617215104798247860771043828666779336684841369949573129138989712352070652644116155611318662052385416920628300517185728354233451887207436923714715196702304603291808807395226466574462454251369421640419450314203453862646939357085161313395870091994536705997276431050332778874671087204270866459209290636957209904296387111707222119192461056);

assign xor_ln26_3_fu_599_p2 = (shl_ln25_6_fu_387_p2 ^ 2056'd8273153554255617868983008432299507701873690283447163912225368429446311715550180068658483561349865846704311797996005892990494607142525675800342567010930760478881504606029054999488050624099750939339790755426321297478858807972510657577430552150649899640468901338121294090979219428234512847003533414175726178693610069347755095659695353545360529790683181065043538446867918248788742705333365840422466199773229341881841562551926235483545177894989221351527346588987721531194144175285969973689640218042094418808237706900648114671371775300698367651383174442595695957899162146670906778789201530522867749937550298524431256635047680);

assign xor_ln26_fu_409_p2 = (zext_ln25_2_fu_301_p1 ^ 2033'd986236757547332986472011617696226561292849812918563355472727826767720188564083584387121625107510786855734801053524719833194566624465665316622563244215340671405971599343902468620306327831715457360719532421388780770165778156818229863337344187575566725786793391480600129482653072861971002459947277805295727097226389568776499707662505334062639449916265137796823793276300221537201727072401742985542559596685092673521228140822200236743113743661549252453726123450722876929538747702356573783116366629850199080495560991841329893037292397105499226019760899853193278062243717512000415180826369586332768194383418384126574591);

assign y_fu_196_p4 = {{pointcloud_q0[15:8]}};

assign zext_ln19_fu_166_p1 = ap_sig_allocacmp_i_1;

assign zext_ln23_1_fu_224_p1 = add_ln23_fu_218_p2;

assign zext_ln23_fu_214_p1 = y_fu_196_p4;

assign zext_ln25_10_fu_363_p1 = shl_ln25_4_fu_357_p2;

assign zext_ln25_11_fu_367_p1 = lshr_ln_fu_249_p4;

assign zext_ln25_1_fu_291_p1 = or_ln1_fu_283_p3;

assign zext_ln25_2_fu_301_p1 = shl_ln25_fu_295_p2;

assign zext_ln25_3_fu_305_p1 = x_reg_658;

assign zext_ln25_4_fu_322_p1 = or_ln25_1_fu_314_p3;

assign zext_ln25_5_fu_332_p1 = shl_ln25_2_fu_326_p2;

assign zext_ln25_6_fu_336_p1 = y_reg_663;

assign zext_ln25_7_fu_383_p1 = add_ln25_fu_377_p2;

assign zext_ln25_8_fu_393_p1 = lshr_ln25_1_fu_258_p4;

assign zext_ln25_9_fu_353_p1 = or_ln25_2_fu_345_p3;

assign zext_ln25_fu_279_p1 = shl_ln_fu_271_p3;

endmodule //calculate_pseudoimage
