// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calculate_pseudoimage_calculate_pseudoimage,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku025-ffva1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.676000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=5034,HLS_SYN_LUT=9920,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module calculate_pseudoimage (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pointcloud_address0,
        pointcloud_ce0,
        pointcloud_q0,
        pseudoimage_count_address0,
        pseudoimage_count_ce0,
        pseudoimage_count_we0,
        pseudoimage_count_d0,
        pseudoimage_count_q0,
        pseudoimage_data_address0,
        pseudoimage_data_ce0,
        pseudoimage_data_we0,
        pseudoimage_data_d0,
        pseudoimage_data_q0,
        pseudoimage_data_address1,
        pseudoimage_data_ce1,
        pseudoimage_data_q1
);

parameter    ap_ST_fsm_state1 = 35'd1;
parameter    ap_ST_fsm_state2 = 35'd2;
parameter    ap_ST_fsm_state3 = 35'd4;
parameter    ap_ST_fsm_state4 = 35'd8;
parameter    ap_ST_fsm_state5 = 35'd16;
parameter    ap_ST_fsm_state6 = 35'd32;
parameter    ap_ST_fsm_state7 = 35'd64;
parameter    ap_ST_fsm_state8 = 35'd128;
parameter    ap_ST_fsm_state9 = 35'd256;
parameter    ap_ST_fsm_state10 = 35'd512;
parameter    ap_ST_fsm_state11 = 35'd1024;
parameter    ap_ST_fsm_state12 = 35'd2048;
parameter    ap_ST_fsm_state13 = 35'd4096;
parameter    ap_ST_fsm_state14 = 35'd8192;
parameter    ap_ST_fsm_state15 = 35'd16384;
parameter    ap_ST_fsm_state16 = 35'd32768;
parameter    ap_ST_fsm_state17 = 35'd65536;
parameter    ap_ST_fsm_state18 = 35'd131072;
parameter    ap_ST_fsm_state19 = 35'd262144;
parameter    ap_ST_fsm_state20 = 35'd524288;
parameter    ap_ST_fsm_state21 = 35'd1048576;
parameter    ap_ST_fsm_state22 = 35'd2097152;
parameter    ap_ST_fsm_state23 = 35'd4194304;
parameter    ap_ST_fsm_state24 = 35'd8388608;
parameter    ap_ST_fsm_state25 = 35'd16777216;
parameter    ap_ST_fsm_state26 = 35'd33554432;
parameter    ap_ST_fsm_state27 = 35'd67108864;
parameter    ap_ST_fsm_state28 = 35'd134217728;
parameter    ap_ST_fsm_state29 = 35'd268435456;
parameter    ap_ST_fsm_state30 = 35'd536870912;
parameter    ap_ST_fsm_state31 = 35'd1073741824;
parameter    ap_ST_fsm_state32 = 35'd2147483648;
parameter    ap_ST_fsm_state33 = 35'd4294967296;
parameter    ap_ST_fsm_state34 = 35'd8589934592;
parameter    ap_ST_fsm_state35 = 35'd17179869184;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] pointcloud_address0;
output   pointcloud_ce0;
input  [255:0] pointcloud_q0;
output  [13:0] pseudoimage_count_address0;
output   pseudoimage_count_ce0;
output   pseudoimage_count_we0;
output  [31:0] pseudoimage_count_d0;
input  [31:0] pseudoimage_count_q0;
output  [19:0] pseudoimage_data_address0;
output   pseudoimage_data_ce0;
output   pseudoimage_data_we0;
output  [575:0] pseudoimage_data_d0;
input  [575:0] pseudoimage_data_q0;
output  [19:0] pseudoimage_data_address1;
output   pseudoimage_data_ce1;
input  [575:0] pseudoimage_data_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] pseudoimage_count_address0;
reg pseudoimage_count_ce0;
reg pseudoimage_count_we0;
reg[19:0] pseudoimage_data_address0;
reg pseudoimage_data_ce0;
reg pseudoimage_data_we0;
reg[575:0] pseudoimage_data_d0;
reg pseudoimage_data_ce1;

(* fsm_encoding = "none" *) reg   [34:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_fu_162_p2;
reg   [63:0] reg_193;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state33;
wire   [63:0] grp_fu_167_p2;
reg   [63:0] reg_199;
wire    ap_CS_fsm_state6;
reg   [31:0] x_reg_332;
wire    ap_CS_fsm_state7;
reg   [31:0] y_reg_337;
wire   [13:0] add_ln60_fu_254_p2;
reg   [13:0] add_ln60_reg_342;
reg   [31:0] pseudoimage_count_load_reg_352;
wire    ap_CS_fsm_state8;
wire   [19:0] tmp_fu_265_p3;
reg   [19:0] tmp_reg_359;
wire    ap_CS_fsm_state10;
wire   [63:0] grp_fu_186_p1;
reg   [63:0] conv1_reg_365;
wire    ap_CS_fsm_state11;
reg   [63:0] conv2_reg_381;
wire    ap_CS_fsm_state23;
wire   [63:0] grp_fu_190_p1;
reg   [63:0] conv3_reg_386;
wire   [63:0] grp_fu_174_p2;
reg   [63:0] avg_x_reg_391;
wire   [63:0] grp_fu_178_p2;
reg   [63:0] avg_y_reg_396;
wire   [63:0] grp_fu_182_p2;
reg   [63:0] avg_z_reg_401;
reg   [9:0] indices_address0;
reg    indices_ce0;
reg    indices_we0;
reg   [31:0] indices_d0;
wire   [31:0] indices_q0;
reg   [9:0] indices_first_address0;
reg    indices_first_ce0;
reg    indices_first_we0;
reg   [31:0] indices_first_d0;
wire   [31:0] indices_first_q0;
wire    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start;
wire    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done;
wire    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_idle;
wire    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_ready;
wire   [9:0] grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_address0;
wire    grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_ce0;
wire    grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_we0;
wire   [31:0] grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_d0;
wire   [9:0] grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_address0;
wire    grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_ce0;
wire    grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_we0;
wire   [31:0] grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_d0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_idle;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_ready;
wire   [9:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_address0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_ce0;
wire   [13:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_address0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_ce0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_we0;
wire   [31:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_d0;
wire   [19:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_address0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_ce0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_we0;
wire   [575:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_d0;
wire   [9:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_address0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_ce0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_we0;
wire   [31:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_d0;
wire   [9:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_address0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_ce0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_we0;
wire   [31:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_d0;
wire   [31:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out_ap_vld;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din0;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din1;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_ce;
wire   [31:0] grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_din0;
wire    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_ce;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_idle;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_ready;
wire   [19:0] grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_address0;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_ce0;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out_ap_vld;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out_ap_vld;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out_ap_vld;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din0;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din1;
wire   [0:0] grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_opcode;
wire    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_ce;
wire    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start;
wire    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done;
wire    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_idle;
wire    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_ready;
wire   [19:0] grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address0;
wire    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce0;
wire    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_we0;
wire   [575:0] grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_d0;
wire   [19:0] grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address1;
wire    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce1;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din0;
wire   [63:0] grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din1;
wire   [0:0] grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_opcode;
wire    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_ce;
reg    grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg;
reg    grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state35;
wire   [63:0] zext_ln52_fu_227_p1;
wire   [0:0] icmp_ln52_fu_216_p2;
wire   [63:0] zext_ln60_fu_260_p1;
reg   [31:0] i_1_fu_52;
wire   [31:0] add_ln52_fu_221_p2;
wire    ap_CS_fsm_state12;
reg    indices_ce0_local;
reg    indices_first_ce0_local;
reg    pseudoimage_count_ce0_local;
reg   [63:0] grp_fu_162_p0;
reg   [63:0] grp_fu_162_p1;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state29;
reg   [63:0] grp_fu_167_p0;
reg   [63:0] grp_fu_167_p1;
reg   [63:0] grp_fu_174_p0;
reg   [63:0] grp_fu_174_p1;
reg   [31:0] grp_fu_186_p0;
wire    ap_CS_fsm_state20;
wire   [6:0] trunc_ln53_fu_238_p1;
wire   [13:0] tmp_s_fu_242_p3;
wire   [13:0] trunc_ln60_fu_250_p1;
reg    grp_fu_174_ce;
reg    grp_fu_186_ce;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire   [63:0] grp_fu_406_p2;
reg   [63:0] grp_fu_406_p0;
reg   [63:0] grp_fu_406_p1;
reg   [1:0] grp_fu_406_opcode;
reg    grp_fu_406_ce;
reg   [34:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
reg    ap_ST_fsm_state35_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 35'd1;
#0 grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg = 1'b0;
#0 grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg = 1'b0;
#0 grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg = 1'b0;
#0 grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg = 1'b0;
#0 i_1_fu_52 = 32'd0;
end

calculate_pseudoimage_indices_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1000 ),
    .AddressWidth( 10 ))
indices_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(indices_address0),
    .ce0(indices_ce0),
    .we0(indices_we0),
    .d0(indices_d0),
    .q0(indices_q0)
);

calculate_pseudoimage_indices_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1000 ),
    .AddressWidth( 10 ))
indices_first_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(indices_first_address0),
    .ce0(indices_first_ce0),
    .we0(indices_first_we0),
    .d0(indices_first_d0),
    .q0(indices_first_q0)
);

calculate_pseudoimage_calculate_pseudoimage_Pipeline_1 grp_calculate_pseudoimage_Pipeline_1_fu_117(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start),
    .ap_done(grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done),
    .ap_idle(grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_idle),
    .ap_ready(grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_ready),
    .indices_address0(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_address0),
    .indices_ce0(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_ce0),
    .indices_we0(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_we0),
    .indices_d0(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_d0),
    .indices_first_address0(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_address0),
    .indices_first_ce0(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_ce0),
    .indices_first_we0(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_we0),
    .indices_first_d0(grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_d0)
);

calculate_pseudoimage_calculate_pseudoimage_Pipeline_collection_loop grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start),
    .ap_done(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done),
    .ap_idle(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_idle),
    .ap_ready(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_ready),
    .pointcloud_address0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_address0),
    .pointcloud_ce0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_ce0),
    .pointcloud_q0(pointcloud_q0),
    .pseudoimage_count_address0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_address0),
    .pseudoimage_count_ce0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_ce0),
    .pseudoimage_count_we0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_we0),
    .pseudoimage_count_d0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_d0),
    .pseudoimage_count_q0(pseudoimage_count_q0),
    .pseudoimage_data_address0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_address0),
    .pseudoimage_data_ce0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_ce0),
    .pseudoimage_data_we0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_we0),
    .pseudoimage_data_d0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_d0),
    .pseudoimage_data_q0(pseudoimage_data_q0),
    .indices_address0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_address0),
    .indices_ce0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_ce0),
    .indices_we0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_we0),
    .indices_d0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_d0),
    .indices_first_address0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_address0),
    .indices_first_ce0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_ce0),
    .indices_first_we0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_we0),
    .indices_first_d0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_d0),
    .pillar_count_out(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out),
    .pillar_count_out_ap_vld(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out_ap_vld),
    .grp_fu_174_p_din0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din0),
    .grp_fu_174_p_din1(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din1),
    .grp_fu_174_p_dout0(grp_fu_174_p2),
    .grp_fu_174_p_ce(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_ce),
    .grp_fu_186_p_din0(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_din0),
    .grp_fu_186_p_dout0(grp_fu_186_p1),
    .grp_fu_186_p_ce(grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_ce)
);

calculate_pseudoimage_calculate_pseudoimage_Pipeline_sum_loop grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start),
    .ap_done(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done),
    .ap_idle(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_idle),
    .ap_ready(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_ready),
    .pseudoimage_count_load(pseudoimage_count_load_reg_352),
    .empty(tmp_reg_359),
    .pseudoimage_data_address0(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_address0),
    .pseudoimage_data_ce0(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_ce0),
    .pseudoimage_data_q0(pseudoimage_data_q0),
    .avg_z_1_out(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out),
    .avg_z_1_out_ap_vld(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out_ap_vld),
    .avg_y_1_out(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out),
    .avg_y_1_out_ap_vld(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out_ap_vld),
    .avg_x_1_out(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out),
    .avg_x_1_out_ap_vld(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out_ap_vld),
    .grp_fu_406_p_din0(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din0),
    .grp_fu_406_p_din1(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din1),
    .grp_fu_406_p_opcode(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_opcode),
    .grp_fu_406_p_dout0(grp_fu_406_p2),
    .grp_fu_406_p_ce(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_ce)
);

calculate_pseudoimage_calculate_pseudoimage_Pipeline_assign_loop grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start),
    .ap_done(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done),
    .ap_idle(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_idle),
    .ap_ready(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_ready),
    .pseudoimage_count_load(pseudoimage_count_load_reg_352),
    .empty(tmp_reg_359),
    .pseudoimage_data_address0(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address0),
    .pseudoimage_data_ce0(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce0),
    .pseudoimage_data_we0(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_we0),
    .pseudoimage_data_d0(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_d0),
    .pseudoimage_data_address1(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address1),
    .pseudoimage_data_ce1(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce1),
    .pseudoimage_data_q1(pseudoimage_data_q1),
    .avg_x(avg_x_reg_391),
    .avg_y(avg_y_reg_396),
    .avg_z(avg_z_reg_401),
    .div5(reg_193),
    .div6(reg_199),
    .grp_fu_406_p_din0(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din0),
    .grp_fu_406_p_din1(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din1),
    .grp_fu_406_p_opcode(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_opcode),
    .grp_fu_406_p_dout0(grp_fu_406_p2),
    .grp_fu_406_p_ce(grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_ce)
);

calculate_pseudoimage_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_162_p0),
    .din1(grp_fu_162_p1),
    .ce(1'b1),
    .dout(grp_fu_162_p2)
);

calculate_pseudoimage_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_167_p0),
    .din1(grp_fu_167_p1),
    .ce(1'b1),
    .dout(grp_fu_167_p2)
);

calculate_pseudoimage_ddiv_64ns_64ns_64_22_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 22 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_22_no_dsp_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_174_p0),
    .din1(grp_fu_174_p1),
    .ce(grp_fu_174_ce),
    .dout(grp_fu_174_p2)
);

calculate_pseudoimage_ddiv_64ns_64ns_64_22_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 22 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_22_no_dsp_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_y_1_out),
    .din1(conv1_reg_365),
    .ce(1'b1),
    .dout(grp_fu_178_p2)
);

calculate_pseudoimage_ddiv_64ns_64ns_64_22_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 22 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_22_no_dsp_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_z_1_out),
    .din1(conv1_reg_365),
    .ce(1'b1),
    .dout(grp_fu_182_p2)
);

calculate_pseudoimage_uitodp_32ns_64_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
uitodp_32ns_64_4_no_dsp_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_186_p0),
    .ce(grp_fu_186_ce),
    .dout(grp_fu_186_p1)
);

calculate_pseudoimage_uitodp_32ns_64_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
uitodp_32ns_64_4_no_dsp_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(y_reg_337),
    .ce(1'b1),
    .dout(grp_fu_190_p1)
);

calculate_pseudoimage_dadddsub_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadddsub_64ns_64ns_64_5_full_dsp_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_406_p0),
    .din1(grp_fu_406_p1),
    .opcode(grp_fu_406_opcode),
    .ce(grp_fu_406_ce),
    .dout(grp_fu_406_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg <= 1'b1;
        end else if ((grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_ready == 1'b1)) begin
            grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state34)) begin
            grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg <= 1'b1;
        end else if ((grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_ready == 1'b1)) begin
            grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg <= 1'b1;
        end else if ((grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_ready == 1'b1)) begin
            grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_ready == 1'b1)) begin
            grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_1_fu_52 <= 32'd0;
    end else if (((icmp_ln52_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        i_1_fu_52 <= add_ln52_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln60_reg_342 <= add_ln60_fu_254_p2;
        x_reg_332 <= indices_q0;
        y_reg_337 <= indices_first_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        avg_x_reg_391 <= grp_fu_174_p2;
        avg_y_reg_396 <= grp_fu_178_p2;
        avg_z_reg_401 <= grp_fu_182_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        conv1_reg_365 <= grp_fu_186_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        conv2_reg_381 <= grp_fu_186_p1;
        conv3_reg_386 <= grp_fu_190_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pseudoimage_count_load_reg_352 <= pseudoimage_count_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state28))) begin
        reg_193 <= grp_fu_162_p2;
        reg_199 <= grp_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_reg_359[19 : 6] <= tmp_fu_265_p3[19 : 6];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

always @ (*) begin
    if ((grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done == 1'b0)) begin
        ap_ST_fsm_state35_blk = 1'b1;
    end else begin
        ap_ST_fsm_state35_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln52_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_162_p0 = reg_193;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_162_p0 = conv2_reg_381;
    end else begin
        grp_fu_162_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_162_p1 = 64'd4575657221408423936;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_162_p1 = 64'd4647503709213818880;
    end else begin
        grp_fu_162_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_167_p0 = reg_199;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_167_p0 = conv3_reg_386;
    end else begin
        grp_fu_167_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_167_p1 = 64'd4575657221408423936;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_167_p1 = 64'd4647503709213818880;
    end else begin
        grp_fu_167_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_174_ce = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_ce;
    end else begin
        grp_fu_174_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_174_p0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_174_p0 = grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_avg_x_1_out;
    end else begin
        grp_fu_174_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_174_p1 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_174_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_174_p1 = conv1_reg_365;
    end else begin
        grp_fu_174_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_186_ce = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | ((grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_fu_186_ce = 1'b1;
    end else begin
        grp_fu_186_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_186_p0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_grp_fu_186_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_186_p0 = x_reg_332;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_186_p0 = pseudoimage_count_q0;
    end else begin
        grp_fu_186_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_406_ce = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_406_ce = grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_ce;
    end else begin
        grp_fu_406_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_406_opcode = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_406_opcode = grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_opcode;
    end else begin
        grp_fu_406_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_406_p0 = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_406_p0 = grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din0;
    end else begin
        grp_fu_406_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_406_p1 = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_grp_fu_406_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_406_p1 = grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_grp_fu_406_p_din1;
    end else begin
        grp_fu_406_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indices_address0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indices_address0 = grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_address0;
    end else begin
        indices_address0 = zext_ln52_fu_227_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indices_ce0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indices_ce0 = grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_ce0;
    end else begin
        indices_ce0 = indices_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        indices_ce0_local = 1'b1;
    end else begin
        indices_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indices_d0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indices_d0 = grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_d0;
    end else begin
        indices_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indices_first_address0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indices_first_address0 = grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_address0;
    end else begin
        indices_first_address0 = zext_ln52_fu_227_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indices_first_ce0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indices_first_ce0 = grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_ce0;
    end else begin
        indices_first_ce0 = indices_first_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        indices_first_ce0_local = 1'b1;
    end else begin
        indices_first_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indices_first_d0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indices_first_d0 = grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_d0;
    end else begin
        indices_first_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indices_first_we0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_first_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indices_first_we0 = grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_first_we0;
    end else begin
        indices_first_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indices_we0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_indices_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indices_we0 = grp_calculate_pseudoimage_Pipeline_1_fu_117_indices_we0;
    end else begin
        indices_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pseudoimage_count_address0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_address0;
    end else begin
        pseudoimage_count_address0 = zext_ln60_fu_260_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pseudoimage_count_ce0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_ce0;
    end else begin
        pseudoimage_count_ce0 = pseudoimage_count_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        pseudoimage_count_ce0_local = 1'b1;
    end else begin
        pseudoimage_count_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pseudoimage_count_we0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_we0;
    end else begin
        pseudoimage_count_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        pseudoimage_data_address0 = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        pseudoimage_data_address0 = grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pseudoimage_data_address0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_address0;
    end else begin
        pseudoimage_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        pseudoimage_data_ce0 = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        pseudoimage_data_ce0 = grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_pseudoimage_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pseudoimage_data_ce0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_ce0;
    end else begin
        pseudoimage_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        pseudoimage_data_ce1 = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_ce1;
    end else begin
        pseudoimage_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        pseudoimage_data_d0 = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pseudoimage_data_d0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_d0;
    end else begin
        pseudoimage_data_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        pseudoimage_data_we0 = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pseudoimage_data_we0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_data_we0;
    end else begin
        pseudoimage_data_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln52_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if (((grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_221_p2 = (i_1_fu_52 + 32'd1);

assign add_ln60_fu_254_p2 = (tmp_s_fu_242_p3 + trunc_ln60_fu_250_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start = grp_calculate_pseudoimage_Pipeline_1_fu_117_ap_start_reg;

assign grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_ap_start_reg;

assign grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_ap_start_reg;

assign grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start = grp_calculate_pseudoimage_Pipeline_sum_loop_fu_138_ap_start_reg;

assign icmp_ln52_fu_216_p2 = ((i_1_fu_52 == grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pillar_count_out) ? 1'b1 : 1'b0);

assign pointcloud_address0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_address0;

assign pointcloud_ce0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pointcloud_ce0;

assign pseudoimage_count_d0 = grp_calculate_pseudoimage_Pipeline_collection_loop_fu_125_pseudoimage_count_d0;

assign pseudoimage_data_address1 = grp_calculate_pseudoimage_Pipeline_assign_loop_fu_149_pseudoimage_data_address1;

assign tmp_fu_265_p3 = {{add_ln60_reg_342}, {6'd0}};

assign tmp_s_fu_242_p3 = {{trunc_ln53_fu_238_p1}, {7'd0}};

assign trunc_ln53_fu_238_p1 = indices_q0[6:0];

assign trunc_ln60_fu_250_p1 = indices_first_q0[13:0];

assign zext_ln52_fu_227_p1 = i_1_fu_52;

assign zext_ln60_fu_260_p1 = add_ln60_fu_254_p2;

always @ (posedge ap_clk) begin
    tmp_reg_359[5:0] <= 6'b000000;
end

endmodule //calculate_pseudoimage
