// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module pointpillars_cnn_p_ZZ16pointpillars_cnnP9PointXYZIiP6BBox3DRiPA4_A3_A3_8ap_fixedILi16ELi6EL9apflZ (
    address0, ce0,
    d0, we0,
    q0,
    address1, ce1,
    d1, we1,
    reset, clk);

parameter DataWidth = 16;
parameter AddressWidth = 9;
parameter AddressRange = 484;

input [AddressWidth-1:0] address0;
input ce0;
input [DataWidth-1:0] d0;
input we0;
output reg [DataWidth-1:0] q0;
input [AddressWidth-1:0] address1;
input ce1;
input [DataWidth-1:0] d1;
input we1;
input reset;
input clk;

(* ram_style = "auto" *) reg [DataWidth-1:0] ram[0:AddressRange-1];

initial begin
    $readmemh("./pointpillars_cnn_p_ZZ16pointpillars_cnnP9PointXYZIiP6BBox3DRiPA4_A3_A3_8ap_fixedILi16ELi6EL9apflZ.dat", ram);
end

// read first
always @(posedge clk)
begin
    if (ce0)
    begin
        if (we0)
            ram[address0] <= d0;
        q0 <= ram[address0];
    end
end

always @(posedge clk)
begin
    if (ce1)
    begin
        if (we1)
            ram[address1] <= d1;
    end
end


endmodule

