// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module calculate_pseudoimage_calculate_pseudoimage_Pipeline_collection_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pointcloud_address0,
        pointcloud_ce0,
        pointcloud_q0,
        pseudoimage_count_address0,
        pseudoimage_count_ce0,
        pseudoimage_count_we0,
        pseudoimage_count_d0,
        pseudoimage_count_q0,
        pseudoimage_data_address0,
        pseudoimage_data_ce0,
        pseudoimage_data_we0,
        pseudoimage_data_d0,
        pseudoimage_data_q0,
        indices_address0,
        indices_ce0,
        indices_we0,
        indices_d0,
        indices_first_address0,
        indices_first_ce0,
        indices_first_we0,
        indices_first_d0,
        pillar_count_out,
        pillar_count_out_ap_vld,
        grp_fu_174_p_din0,
        grp_fu_174_p_din1,
        grp_fu_174_p_dout0,
        grp_fu_174_p_ce,
        grp_fu_186_p_din0,
        grp_fu_186_p_dout0,
        grp_fu_186_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] pointcloud_address0;
output   pointcloud_ce0;
input  [255:0] pointcloud_q0;
output  [13:0] pseudoimage_count_address0;
output   pseudoimage_count_ce0;
output   pseudoimage_count_we0;
output  [31:0] pseudoimage_count_d0;
input  [31:0] pseudoimage_count_q0;
output  [19:0] pseudoimage_data_address0;
output   pseudoimage_data_ce0;
output   pseudoimage_data_we0;
output  [575:0] pseudoimage_data_d0;
input  [575:0] pseudoimage_data_q0;
output  [9:0] indices_address0;
output   indices_ce0;
output   indices_we0;
output  [31:0] indices_d0;
output  [9:0] indices_first_address0;
output   indices_first_ce0;
output   indices_first_we0;
output  [31:0] indices_first_d0;
output  [31:0] pillar_count_out;
output   pillar_count_out_ap_vld;
output  [63:0] grp_fu_174_p_din0;
output  [63:0] grp_fu_174_p_din1;
input  [63:0] grp_fu_174_p_dout0;
output   grp_fu_174_p_ce;
output  [31:0] grp_fu_186_p_din0;
input  [63:0] grp_fu_186_p_dout0;
output   grp_fu_186_p_ce;

reg ap_idle;
reg pillar_count_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln32_reg_844;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln32_fu_217_p2;
reg   [0:0] icmp_ln32_reg_844_pp0_iter1_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter2_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter3_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter4_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter5_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter6_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter7_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter8_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter9_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter10_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter11_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter12_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter13_reg;
reg   [0:0] icmp_ln32_reg_844_pp0_iter14_reg;
wire   [63:0] zext_ln32_fu_229_p1;
reg   [63:0] zext_ln32_reg_848;
reg   [63:0] zext_ln32_reg_848_pp0_iter1_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter2_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter3_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter4_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter5_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter6_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter7_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter8_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter9_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter10_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter11_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter12_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter13_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter14_reg;
reg   [63:0] zext_ln32_reg_848_pp0_iter15_reg;
reg   [255:0] pointcloud_load_reg_859;
wire    ap_block_pp0_stage1_11001;
reg   [255:0] pointcloud_load_reg_859_pp0_iter1_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter2_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter3_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter4_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter5_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter6_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter7_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter8_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter9_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter10_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter11_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter12_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter13_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter14_reg;
reg   [255:0] pointcloud_load_reg_859_pp0_iter15_reg;
wire   [24:0] select_ln71_1_fu_343_p3;
reg   [24:0] select_ln71_1_reg_864;
wire   [24:0] select_ln71_5_fu_461_p3;
reg   [24:0] select_ln71_5_reg_869;
wire   [31:0] and_ln_fu_469_p3;
wire   [31:0] and_ln1_fu_477_p3;
reg   [63:0] conv4_reg_884;
reg   [63:0] conv_reg_889;
reg   [10:0] xs_exp_1_reg_894;
reg   [10:0] xs_exp_1_reg_894_pp0_iter14_reg;
wire   [51:0] trunc_ln505_1_fu_497_p1;
reg   [51:0] trunc_ln505_1_reg_900;
reg   [51:0] trunc_ln505_1_reg_900_pp0_iter14_reg;
reg   [10:0] xs_exp_3_reg_905;
wire   [51:0] trunc_ln505_2_fu_513_p1;
reg   [51:0] trunc_ln505_2_reg_911;
wire   [31:0] val_fu_604_p3;
reg   [31:0] val_reg_916;
wire   [31:0] val_1_fu_703_p3;
reg   [31:0] val_1_reg_921;
wire   [13:0] add_ln36_fu_723_p2;
reg   [13:0] add_ln36_reg_926;
reg   [13:0] pseudoimage_count_addr_reg_931;
wire   [0:0] icmp_ln37_fu_755_p2;
reg   [0:0] icmp_ln37_reg_936;
reg   [19:0] pseudoimage_data_addr_reg_943;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln36_fu_729_p1;
wire    ap_block_pp0_stage1;
wire   [0:0] icmp_ln38_fu_761_p2;
wire   [63:0] zext_ln43_fu_791_p1;
reg   [9:0] i_fu_116;
wire   [9:0] add_ln32_fu_223_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_1;
reg   [31:0] pillar_count_fu_120;
wire   [31:0] pillar_count_1_fu_770_p2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter15_stage0;
reg    ap_idle_pp0_0to14;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
wire    ap_block_pp0_stage0_01001;
reg    pointcloud_ce0_local;
reg    pseudoimage_count_ce0_local;
reg   [13:0] pseudoimage_count_address0_local;
reg    pseudoimage_count_we0_local;
wire   [31:0] zext_ln48_fu_802_p1;
reg    indices_we0_local;
reg    indices_ce0_local;
reg    indices_first_we0_local;
reg    indices_first_ce0_local;
reg    pseudoimage_data_ce0_local;
reg   [19:0] pseudoimage_data_address0_local;
reg    pseudoimage_data_we0_local;
wire   [575:0] or_ln46_3_fu_817_p3;
reg   [63:0] grp_fu_196_p0;
reg   [31:0] grp_fu_201_p0;
wire   [51:0] trunc_ln505_fu_249_p1;
wire   [53:0] mantissa_fu_253_p4;
wire   [10:0] xs_exp_fu_239_p4;
wire   [11:0] zext_ln486_fu_267_p1;
wire   [11:0] add_ln486_fu_271_p2;
wire   [10:0] sub_ln71_fu_285_p2;
wire   [0:0] tmp_9_fu_277_p3;
wire  signed [11:0] sext_ln71_fu_291_p1;
wire   [11:0] select_ln71_fu_295_p3;
wire  signed [31:0] sext_ln71_1_fu_303_p1;
wire   [136:0] zext_ln68_fu_263_p1;
wire   [136:0] zext_ln71_fu_307_p1;
wire   [136:0] lshr_ln71_fu_311_p2;
wire   [136:0] shl_ln71_fu_317_p2;
wire   [24:0] tmp_fu_323_p4;
wire   [24:0] tmp_1_fu_333_p4;
wire   [51:0] tmp_i1_fu_361_p4;
wire   [53:0] mantissa_2_fu_371_p4;
wire   [10:0] xs_exp_2_fu_351_p4;
wire   [11:0] zext_ln486_2_fu_385_p1;
wire   [11:0] add_ln486_2_fu_389_p2;
wire   [10:0] sub_ln71_2_fu_403_p2;
wire   [0:0] tmp_11_fu_395_p3;
wire  signed [11:0] sext_ln71_4_fu_409_p1;
wire   [11:0] select_ln71_4_fu_413_p3;
wire  signed [31:0] sext_ln71_5_fu_421_p1;
wire   [136:0] zext_ln68_2_fu_381_p1;
wire   [136:0] zext_ln71_2_fu_425_p1;
wire   [136:0] lshr_ln71_2_fu_429_p2;
wire   [136:0] shl_ln71_2_fu_435_p2;
wire   [24:0] tmp_4_fu_441_p4;
wire   [24:0] tmp_5_fu_451_p4;
wire   [63:0] data_fu_485_p1;
wire   [63:0] data_1_fu_501_p1;
wire   [53:0] mantissa_1_fu_517_p4;
wire   [11:0] zext_ln486_1_fu_530_p1;
wire   [11:0] add_ln486_1_fu_533_p2;
wire   [10:0] sub_ln71_1_fu_547_p2;
wire   [0:0] tmp_10_fu_539_p3;
wire  signed [11:0] sext_ln71_2_fu_552_p1;
wire   [11:0] select_ln71_2_fu_556_p3;
wire  signed [31:0] sext_ln71_3_fu_564_p1;
wire   [136:0] zext_ln68_1_fu_526_p1;
wire   [136:0] zext_ln71_1_fu_568_p1;
wire   [136:0] lshr_ln71_1_fu_572_p2;
wire   [136:0] shl_ln71_1_fu_578_p2;
wire   [31:0] tmp_2_fu_584_p4;
wire   [31:0] tmp_3_fu_594_p4;
wire   [53:0] mantissa_3_fu_616_p4;
wire   [11:0] zext_ln486_3_fu_629_p1;
wire   [11:0] add_ln486_3_fu_632_p2;
wire   [10:0] sub_ln71_3_fu_646_p2;
wire   [0:0] tmp_12_fu_638_p3;
wire  signed [11:0] sext_ln71_6_fu_651_p1;
wire   [11:0] select_ln71_6_fu_655_p3;
wire  signed [31:0] sext_ln71_7_fu_663_p1;
wire   [136:0] zext_ln68_3_fu_625_p1;
wire   [136:0] zext_ln71_3_fu_667_p1;
wire   [136:0] lshr_ln71_3_fu_671_p2;
wire   [136:0] shl_ln71_3_fu_677_p2;
wire   [31:0] tmp_6_fu_683_p4;
wire   [31:0] tmp_7_fu_693_p4;
wire   [6:0] trunc_ln74_fu_612_p1;
wire   [13:0] tmp_8_fu_711_p3;
wire   [13:0] trunc_ln36_fu_719_p1;
wire   [25:0] tmp_15_fu_745_p4;
wire   [19:0] tmp_13_fu_734_p3;
wire   [19:0] trunc_ln43_fu_781_p1;
wire   [19:0] add_ln43_fu_785_p2;
wire   [6:0] trunc_ln36_1_fu_741_p1;
wire   [6:0] add_ln48_fu_796_p2;
wire   [319:0] tmp_s_fu_807_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_116 = 10'd0;
#0 pillar_count_fu_120 = 32'd0;
#0 ap_done_reg = 1'b0;
end

calculate_pseudoimage_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter16 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln32_fu_217_p2 == 1'd0))) begin
            i_fu_116 <= add_ln32_fu_223_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_116 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pillar_count_fu_120 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln38_fu_761_p2 == 1'd1) & (icmp_ln37_fu_755_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pillar_count_fu_120 <= pillar_count_1_fu_770_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln36_reg_926 <= add_ln36_fu_723_p2;
        icmp_ln32_reg_844 <= icmp_ln32_fu_217_p2;
        icmp_ln32_reg_844_pp0_iter10_reg <= icmp_ln32_reg_844_pp0_iter9_reg;
        icmp_ln32_reg_844_pp0_iter11_reg <= icmp_ln32_reg_844_pp0_iter10_reg;
        icmp_ln32_reg_844_pp0_iter12_reg <= icmp_ln32_reg_844_pp0_iter11_reg;
        icmp_ln32_reg_844_pp0_iter13_reg <= icmp_ln32_reg_844_pp0_iter12_reg;
        icmp_ln32_reg_844_pp0_iter14_reg <= icmp_ln32_reg_844_pp0_iter13_reg;
        icmp_ln32_reg_844_pp0_iter1_reg <= icmp_ln32_reg_844;
        icmp_ln32_reg_844_pp0_iter2_reg <= icmp_ln32_reg_844_pp0_iter1_reg;
        icmp_ln32_reg_844_pp0_iter3_reg <= icmp_ln32_reg_844_pp0_iter2_reg;
        icmp_ln32_reg_844_pp0_iter4_reg <= icmp_ln32_reg_844_pp0_iter3_reg;
        icmp_ln32_reg_844_pp0_iter5_reg <= icmp_ln32_reg_844_pp0_iter4_reg;
        icmp_ln32_reg_844_pp0_iter6_reg <= icmp_ln32_reg_844_pp0_iter5_reg;
        icmp_ln32_reg_844_pp0_iter7_reg <= icmp_ln32_reg_844_pp0_iter6_reg;
        icmp_ln32_reg_844_pp0_iter8_reg <= icmp_ln32_reg_844_pp0_iter7_reg;
        icmp_ln32_reg_844_pp0_iter9_reg <= icmp_ln32_reg_844_pp0_iter8_reg;
        pseudoimage_count_addr_reg_931 <= zext_ln36_fu_729_p1;
        trunc_ln505_2_reg_911 <= trunc_ln505_2_fu_513_p1;
        val_1_reg_921 <= val_1_fu_703_p3;
        val_reg_916 <= val_fu_604_p3;
        xs_exp_3_reg_905 <= {{data_1_fu_501_p1[62:52]}};
        zext_ln32_reg_848[9 : 0] <= zext_ln32_fu_229_p1[9 : 0];
        zext_ln32_reg_848_pp0_iter10_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter9_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter11_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter10_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter12_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter11_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter13_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter12_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter14_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter13_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter15_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter14_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter1_reg[9 : 0] <= zext_ln32_reg_848[9 : 0];
        zext_ln32_reg_848_pp0_iter2_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter1_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter3_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter2_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter4_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter3_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter5_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter4_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter6_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter5_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter7_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter6_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter8_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter7_reg[9 : 0];
        zext_ln32_reg_848_pp0_iter9_reg[9 : 0] <= zext_ln32_reg_848_pp0_iter8_reg[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        conv4_reg_884 <= grp_fu_186_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_reg_889 <= grp_fu_186_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln37_reg_936 <= icmp_ln37_fu_755_p2;
        pointcloud_load_reg_859 <= pointcloud_q0;
        pointcloud_load_reg_859_pp0_iter10_reg <= pointcloud_load_reg_859_pp0_iter9_reg;
        pointcloud_load_reg_859_pp0_iter11_reg <= pointcloud_load_reg_859_pp0_iter10_reg;
        pointcloud_load_reg_859_pp0_iter12_reg <= pointcloud_load_reg_859_pp0_iter11_reg;
        pointcloud_load_reg_859_pp0_iter13_reg <= pointcloud_load_reg_859_pp0_iter12_reg;
        pointcloud_load_reg_859_pp0_iter14_reg <= pointcloud_load_reg_859_pp0_iter13_reg;
        pointcloud_load_reg_859_pp0_iter15_reg <= pointcloud_load_reg_859_pp0_iter14_reg;
        pointcloud_load_reg_859_pp0_iter1_reg <= pointcloud_load_reg_859;
        pointcloud_load_reg_859_pp0_iter2_reg <= pointcloud_load_reg_859_pp0_iter1_reg;
        pointcloud_load_reg_859_pp0_iter3_reg <= pointcloud_load_reg_859_pp0_iter2_reg;
        pointcloud_load_reg_859_pp0_iter4_reg <= pointcloud_load_reg_859_pp0_iter3_reg;
        pointcloud_load_reg_859_pp0_iter5_reg <= pointcloud_load_reg_859_pp0_iter4_reg;
        pointcloud_load_reg_859_pp0_iter6_reg <= pointcloud_load_reg_859_pp0_iter5_reg;
        pointcloud_load_reg_859_pp0_iter7_reg <= pointcloud_load_reg_859_pp0_iter6_reg;
        pointcloud_load_reg_859_pp0_iter8_reg <= pointcloud_load_reg_859_pp0_iter7_reg;
        pointcloud_load_reg_859_pp0_iter9_reg <= pointcloud_load_reg_859_pp0_iter8_reg;
        pseudoimage_data_addr_reg_943 <= zext_ln43_fu_791_p1;
        select_ln71_1_reg_864 <= select_ln71_1_fu_343_p3;
        select_ln71_5_reg_869 <= select_ln71_5_fu_461_p3;
        trunc_ln505_1_reg_900 <= trunc_ln505_1_fu_497_p1;
        trunc_ln505_1_reg_900_pp0_iter14_reg <= trunc_ln505_1_reg_900;
        xs_exp_1_reg_894 <= {{data_fu_485_p1[62:52]}};
        xs_exp_1_reg_894_pp0_iter14_reg <= xs_exp_1_reg_894;
    end
end

always @ (*) begin
    if (((icmp_ln32_reg_844 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln32_reg_844_pp0_iter14_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter15_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter15_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to14 = 1'b1;
    end else begin
        ap_idle_pp0_0to14 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_116;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_196_p0 = conv_reg_889;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_196_p0 = conv4_reg_884;
        end else begin
            grp_fu_196_p0 = 'bx;
        end
    end else begin
        grp_fu_196_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_201_p0 = and_ln1_fu_477_p3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_201_p0 = and_ln_fu_469_p3;
        end else begin
            grp_fu_201_p0 = 'bx;
        end
    end else begin
        grp_fu_201_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indices_ce0_local = 1'b1;
    end else begin
        indices_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indices_first_ce0_local = 1'b1;
    end else begin
        indices_first_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln38_fu_761_p2 == 1'd1) & (icmp_ln37_fu_755_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indices_first_we0_local = 1'b1;
    end else begin
        indices_first_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln38_fu_761_p2 == 1'd1) & (icmp_ln37_fu_755_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indices_we0_local = 1'b1;
    end else begin
        indices_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln32_reg_844_pp0_iter14_reg == 1'd1))) begin
        pillar_count_out_ap_vld = 1'b1;
    end else begin
        pillar_count_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pointcloud_ce0_local = 1'b1;
    end else begin
        pointcloud_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter15 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            pseudoimage_count_address0_local = pseudoimage_count_addr_reg_931;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pseudoimage_count_address0_local = zext_ln36_fu_729_p1;
        end else begin
            pseudoimage_count_address0_local = 'bx;
        end
    end else begin
        pseudoimage_count_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        pseudoimage_count_ce0_local = 1'b1;
    end else begin
        pseudoimage_count_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln37_fu_755_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pseudoimage_count_we0_local = 1'b1;
    end else begin
        pseudoimage_count_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pseudoimage_data_address0_local = pseudoimage_data_addr_reg_943;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pseudoimage_data_address0_local = zext_ln43_fu_791_p1;
    end else begin
        pseudoimage_data_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        pseudoimage_data_ce0_local = 1'b1;
    end else begin
        pseudoimage_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln37_reg_936 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pseudoimage_data_we0_local = 1'b1;
    end else begin
        pseudoimage_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to14 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter15_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_223_p2 = (ap_sig_allocacmp_i_1 + 10'd1);

assign add_ln36_fu_723_p2 = (tmp_8_fu_711_p3 + trunc_ln36_fu_719_p1);

assign add_ln43_fu_785_p2 = (tmp_13_fu_734_p3 + trunc_ln43_fu_781_p1);

assign add_ln486_1_fu_533_p2 = ($signed(zext_ln486_1_fu_530_p1) + $signed(12'd3073));

assign add_ln486_2_fu_389_p2 = ($signed(zext_ln486_2_fu_385_p1) + $signed(12'd3073));

assign add_ln486_3_fu_632_p2 = ($signed(zext_ln486_3_fu_629_p1) + $signed(12'd3073));

assign add_ln486_fu_271_p2 = ($signed(zext_ln486_fu_267_p1) + $signed(12'd3073));

assign add_ln48_fu_796_p2 = (trunc_ln36_1_fu_741_p1 + 7'd1);

assign and_ln1_fu_477_p3 = {{select_ln71_5_reg_869}, {7'd0}};

assign and_ln_fu_469_p3 = {{select_ln71_1_reg_864}, {7'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign data_1_fu_501_p1 = grp_fu_174_p_dout0;

assign data_fu_485_p1 = grp_fu_174_p_dout0;

assign grp_fu_174_p_ce = 1'b1;

assign grp_fu_174_p_din0 = grp_fu_196_p0;

assign grp_fu_174_p_din1 = 64'd4647503709213818880;

assign grp_fu_186_p_ce = 1'b1;

assign grp_fu_186_p_din0 = grp_fu_201_p0;

assign icmp_ln32_fu_217_p2 = ((ap_sig_allocacmp_i_1 == 10'd1000) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_755_p2 = ((tmp_15_fu_745_p4 == 26'd0) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_761_p2 = ((pseudoimage_count_q0 == 32'd0) ? 1'b1 : 1'b0);

assign indices_address0 = zext_ln32_reg_848_pp0_iter15_reg;

assign indices_ce0 = indices_ce0_local;

assign indices_d0 = val_reg_916;

assign indices_first_address0 = zext_ln32_reg_848_pp0_iter15_reg;

assign indices_first_ce0 = indices_first_ce0_local;

assign indices_first_d0 = val_1_reg_921;

assign indices_first_we0 = indices_first_we0_local;

assign indices_we0 = indices_we0_local;

assign lshr_ln71_1_fu_572_p2 = zext_ln68_1_fu_526_p1 >> zext_ln71_1_fu_568_p1;

assign lshr_ln71_2_fu_429_p2 = zext_ln68_2_fu_381_p1 >> zext_ln71_2_fu_425_p1;

assign lshr_ln71_3_fu_671_p2 = zext_ln68_3_fu_625_p1 >> zext_ln71_3_fu_667_p1;

assign lshr_ln71_fu_311_p2 = zext_ln68_fu_263_p1 >> zext_ln71_fu_307_p1;

assign mantissa_1_fu_517_p4 = {{{{1'd1}, {trunc_ln505_1_reg_900_pp0_iter14_reg}}}, {1'd0}};

assign mantissa_2_fu_371_p4 = {{{{1'd1}, {tmp_i1_fu_361_p4}}}, {1'd0}};

assign mantissa_3_fu_616_p4 = {{{{1'd1}, {trunc_ln505_2_reg_911}}}, {1'd0}};

assign mantissa_fu_253_p4 = {{{{1'd1}, {trunc_ln505_fu_249_p1}}}, {1'd0}};

assign or_ln46_3_fu_817_p3 = {{tmp_s_fu_807_p4}, {pointcloud_load_reg_859_pp0_iter15_reg}};

assign pillar_count_1_fu_770_p2 = (pillar_count_fu_120 + 32'd1);

assign pillar_count_out = pillar_count_fu_120;

assign pointcloud_address0 = zext_ln32_fu_229_p1;

assign pointcloud_ce0 = pointcloud_ce0_local;

assign pseudoimage_count_address0 = pseudoimage_count_address0_local;

assign pseudoimage_count_ce0 = pseudoimage_count_ce0_local;

assign pseudoimage_count_d0 = zext_ln48_fu_802_p1;

assign pseudoimage_count_we0 = pseudoimage_count_we0_local;

assign pseudoimage_data_address0 = pseudoimage_data_address0_local;

assign pseudoimage_data_ce0 = pseudoimage_data_ce0_local;

assign pseudoimage_data_d0 = or_ln46_3_fu_817_p3;

assign pseudoimage_data_we0 = pseudoimage_data_we0_local;

assign select_ln71_1_fu_343_p3 = ((tmp_9_fu_277_p3[0:0] == 1'b1) ? tmp_fu_323_p4 : tmp_1_fu_333_p4);

assign select_ln71_2_fu_556_p3 = ((tmp_10_fu_539_p3[0:0] == 1'b1) ? sext_ln71_2_fu_552_p1 : add_ln486_1_fu_533_p2);

assign select_ln71_4_fu_413_p3 = ((tmp_11_fu_395_p3[0:0] == 1'b1) ? sext_ln71_4_fu_409_p1 : add_ln486_2_fu_389_p2);

assign select_ln71_5_fu_461_p3 = ((tmp_11_fu_395_p3[0:0] == 1'b1) ? tmp_4_fu_441_p4 : tmp_5_fu_451_p4);

assign select_ln71_6_fu_655_p3 = ((tmp_12_fu_638_p3[0:0] == 1'b1) ? sext_ln71_6_fu_651_p1 : add_ln486_3_fu_632_p2);

assign select_ln71_fu_295_p3 = ((tmp_9_fu_277_p3[0:0] == 1'b1) ? sext_ln71_fu_291_p1 : add_ln486_fu_271_p2);

assign sext_ln71_1_fu_303_p1 = $signed(select_ln71_fu_295_p3);

assign sext_ln71_2_fu_552_p1 = $signed(sub_ln71_1_fu_547_p2);

assign sext_ln71_3_fu_564_p1 = $signed(select_ln71_2_fu_556_p3);

assign sext_ln71_4_fu_409_p1 = $signed(sub_ln71_2_fu_403_p2);

assign sext_ln71_5_fu_421_p1 = $signed(select_ln71_4_fu_413_p3);

assign sext_ln71_6_fu_651_p1 = $signed(sub_ln71_3_fu_646_p2);

assign sext_ln71_7_fu_663_p1 = $signed(select_ln71_6_fu_655_p3);

assign sext_ln71_fu_291_p1 = $signed(sub_ln71_fu_285_p2);

assign shl_ln71_1_fu_578_p2 = zext_ln68_1_fu_526_p1 << zext_ln71_1_fu_568_p1;

assign shl_ln71_2_fu_435_p2 = zext_ln68_2_fu_381_p1 << zext_ln71_2_fu_425_p1;

assign shl_ln71_3_fu_677_p2 = zext_ln68_3_fu_625_p1 << zext_ln71_3_fu_667_p1;

assign shl_ln71_fu_317_p2 = zext_ln68_fu_263_p1 << zext_ln71_fu_307_p1;

assign sub_ln71_1_fu_547_p2 = (11'd1023 - xs_exp_1_reg_894_pp0_iter14_reg);

assign sub_ln71_2_fu_403_p2 = (11'd1023 - xs_exp_2_fu_351_p4);

assign sub_ln71_3_fu_646_p2 = (11'd1023 - xs_exp_3_reg_905);

assign sub_ln71_fu_285_p2 = (11'd1023 - xs_exp_fu_239_p4);

assign tmp_10_fu_539_p3 = add_ln486_1_fu_533_p2[32'd11];

assign tmp_11_fu_395_p3 = add_ln486_2_fu_389_p2[32'd11];

assign tmp_12_fu_638_p3 = add_ln486_3_fu_632_p2[32'd11];

assign tmp_13_fu_734_p3 = {{add_ln36_reg_926}, {6'd0}};

assign tmp_15_fu_745_p4 = {{pseudoimage_count_q0[31:6]}};

assign tmp_1_fu_333_p4 = {{shl_ln71_fu_317_p2[77:53]}};

assign tmp_2_fu_584_p4 = {{lshr_ln71_1_fu_572_p2[84:53]}};

assign tmp_3_fu_594_p4 = {{shl_ln71_1_fu_578_p2[84:53]}};

assign tmp_4_fu_441_p4 = {{lshr_ln71_2_fu_429_p2[77:53]}};

assign tmp_5_fu_451_p4 = {{shl_ln71_2_fu_435_p2[77:53]}};

assign tmp_6_fu_683_p4 = {{lshr_ln71_3_fu_671_p2[84:53]}};

assign tmp_7_fu_693_p4 = {{shl_ln71_3_fu_677_p2[84:53]}};

assign tmp_8_fu_711_p3 = {{trunc_ln74_fu_612_p1}, {7'd0}};

assign tmp_9_fu_277_p3 = add_ln486_fu_271_p2[32'd11];

assign tmp_fu_323_p4 = {{lshr_ln71_fu_311_p2[77:53]}};

assign tmp_i1_fu_361_p4 = {{pointcloud_q0[115:64]}};

assign tmp_s_fu_807_p4 = {{pseudoimage_data_q0[575:256]}};

assign trunc_ln36_1_fu_741_p1 = pseudoimage_count_q0[6:0];

assign trunc_ln36_fu_719_p1 = val_1_fu_703_p3[13:0];

assign trunc_ln43_fu_781_p1 = pseudoimage_count_q0[19:0];

assign trunc_ln505_1_fu_497_p1 = data_fu_485_p1[51:0];

assign trunc_ln505_2_fu_513_p1 = data_1_fu_501_p1[51:0];

assign trunc_ln505_fu_249_p1 = pointcloud_q0[51:0];

assign trunc_ln74_fu_612_p1 = val_fu_604_p3[6:0];

assign val_1_fu_703_p3 = ((tmp_12_fu_638_p3[0:0] == 1'b1) ? tmp_6_fu_683_p4 : tmp_7_fu_693_p4);

assign val_fu_604_p3 = ((tmp_10_fu_539_p3[0:0] == 1'b1) ? tmp_2_fu_584_p4 : tmp_3_fu_594_p4);

assign xs_exp_2_fu_351_p4 = {{pointcloud_q0[126:116]}};

assign xs_exp_fu_239_p4 = {{pointcloud_q0[62:52]}};

assign zext_ln32_fu_229_p1 = ap_sig_allocacmp_i_1;

assign zext_ln36_fu_729_p1 = add_ln36_fu_723_p2;

assign zext_ln43_fu_791_p1 = add_ln43_fu_785_p2;

assign zext_ln486_1_fu_530_p1 = xs_exp_1_reg_894_pp0_iter14_reg;

assign zext_ln486_2_fu_385_p1 = xs_exp_2_fu_351_p4;

assign zext_ln486_3_fu_629_p1 = xs_exp_3_reg_905;

assign zext_ln486_fu_267_p1 = xs_exp_fu_239_p4;

assign zext_ln48_fu_802_p1 = add_ln48_fu_796_p2;

assign zext_ln68_1_fu_526_p1 = mantissa_1_fu_517_p4;

assign zext_ln68_2_fu_381_p1 = mantissa_2_fu_371_p4;

assign zext_ln68_3_fu_625_p1 = mantissa_3_fu_616_p4;

assign zext_ln68_fu_263_p1 = mantissa_fu_253_p4;

assign zext_ln71_1_fu_568_p1 = $unsigned(sext_ln71_3_fu_564_p1);

assign zext_ln71_2_fu_425_p1 = $unsigned(sext_ln71_5_fu_421_p1);

assign zext_ln71_3_fu_667_p1 = $unsigned(sext_ln71_7_fu_663_p1);

assign zext_ln71_fu_307_p1 = $unsigned(sext_ln71_1_fu_303_p1);

always @ (posedge ap_clk) begin
    zext_ln32_reg_848[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter1_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter2_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter3_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter4_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter5_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter6_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter7_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter8_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter9_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter10_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter11_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter12_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter13_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter14_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_848_pp0_iter15_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //calculate_pseudoimage_calculate_pseudoimage_Pipeline_collection_loop
