// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module calculate_pseudoimage_calculate_pseudoimage_Pipeline_assign_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pseudoimage_count_load,
        empty,
        pseudoimage_data_address0,
        pseudoimage_data_ce0,
        pseudoimage_data_we0,
        pseudoimage_data_d0,
        pseudoimage_data_address1,
        pseudoimage_data_ce1,
        pseudoimage_data_q1,
        avg_x,
        avg_y,
        avg_z,
        div5,
        div6,
        grp_fu_406_p_din0,
        grp_fu_406_p_din1,
        grp_fu_406_p_opcode,
        grp_fu_406_p_dout0,
        grp_fu_406_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] pseudoimage_count_load;
input  [19:0] empty;
output  [19:0] pseudoimage_data_address0;
output   pseudoimage_data_ce0;
output   pseudoimage_data_we0;
output  [575:0] pseudoimage_data_d0;
output  [19:0] pseudoimage_data_address1;
output   pseudoimage_data_ce1;
input  [575:0] pseudoimage_data_q1;
input  [63:0] avg_x;
input  [63:0] avg_y;
input  [63:0] avg_z;
input  [63:0] div5;
input  [63:0] div6;
output  [63:0] grp_fu_406_p_din0;
output  [63:0] grp_fu_406_p_din1;
output  [0:0] grp_fu_406_p_opcode;
input  [63:0] grp_fu_406_p_dout0;
output   grp_fu_406_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln69_fu_153_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [19:0] pseudoimage_data_addr_reg_302;
reg   [19:0] pseudoimage_data_addr_reg_302_pp0_iter1_reg;
reg   [19:0] pseudoimage_data_addr_reg_302_pp0_iter2_reg;
reg   [19:0] pseudoimage_data_addr_reg_302_pp0_iter3_reg;
reg   [19:0] pseudoimage_data_addr_reg_302_pp0_iter4_reg;
wire   [255:0] trunc_ln70_1_fu_185_p1;
reg   [255:0] trunc_ln70_1_reg_308;
reg   [255:0] trunc_ln70_1_reg_308_pp0_iter2_reg;
reg   [255:0] trunc_ln70_1_reg_308_pp0_iter3_reg;
reg   [255:0] trunc_ln70_1_reg_308_pp0_iter4_reg;
wire   [63:0] bitcast_ln70_fu_193_p1;
wire   [63:0] bitcast_ln71_fu_209_p1;
wire   [63:0] zext_ln70_fu_175_p1;
wire    ap_block_pp0_stage0;
reg   [20:0] j_1_fu_58;
wire   [20:0] add_ln69_fu_159_p2;
wire    ap_loop_init;
reg   [20:0] ap_sig_allocacmp_j;
reg    pseudoimage_data_ce1_local;
reg    pseudoimage_data_we0_local;
wire   [575:0] or_ln75_4_fu_250_p7;
reg    pseudoimage_data_ce0_local;
wire   [63:0] grp_fu_129_p0;
wire   [31:0] zext_ln69_fu_149_p1;
wire   [19:0] trunc_ln70_fu_165_p1;
wire   [19:0] add_ln70_fu_169_p2;
wire   [63:0] trunc_ln70_2_fu_189_p1;
wire   [63:0] trunc_ln5_fu_199_p4;
wire   [63:0] trunc_ln6_fu_215_p4;
wire   [63:0] grp_fu_125_p2;
wire   [63:0] grp_fu_129_p2;
wire   [63:0] grp_fu_133_p2;
wire   [63:0] grp_fu_137_p2;
wire   [63:0] bitcast_ln75_fu_246_p1;
wire   [63:0] bitcast_ln74_fu_242_p1;
wire   [63:0] bitcast_ln72_1_fu_238_p1;
wire   [63:0] bitcast_ln71_1_fu_234_p1;
wire   [63:0] bitcast_ln70_1_fu_230_p1;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 j_1_fu_58 = 21'd0;
#0 ap_done_reg = 1'b0;
end

calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsub_64ns_64ns_64_5_full_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln71_fu_209_p1),
    .din1(avg_y),
    .ce(1'b1),
    .dout(grp_fu_125_p2)
);

calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsub_64ns_64ns_64_5_full_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_129_p0),
    .din1(avg_z),
    .ce(1'b1),
    .dout(grp_fu_129_p2)
);

calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsub_64ns_64ns_64_5_full_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln70_fu_193_p1),
    .din1(div5),
    .ce(1'b1),
    .dout(grp_fu_133_p2)
);

calculate_pseudoimage_dsub_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsub_64ns_64ns_64_5_full_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln71_fu_209_p1),
    .din1(div6),
    .ce(1'b1),
    .dout(grp_fu_137_p2)
);

calculate_pseudoimage_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln69_fu_153_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_1_fu_58 <= add_ln69_fu_159_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_1_fu_58 <= 21'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        pseudoimage_data_addr_reg_302 <= zext_ln70_fu_175_p1;
        pseudoimage_data_addr_reg_302_pp0_iter1_reg <= pseudoimage_data_addr_reg_302;
        trunc_ln70_1_reg_308 <= trunc_ln70_1_fu_185_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        pseudoimage_data_addr_reg_302_pp0_iter2_reg <= pseudoimage_data_addr_reg_302_pp0_iter1_reg;
        pseudoimage_data_addr_reg_302_pp0_iter3_reg <= pseudoimage_data_addr_reg_302_pp0_iter2_reg;
        pseudoimage_data_addr_reg_302_pp0_iter4_reg <= pseudoimage_data_addr_reg_302_pp0_iter3_reg;
        trunc_ln70_1_reg_308_pp0_iter2_reg <= trunc_ln70_1_reg_308;
        trunc_ln70_1_reg_308_pp0_iter3_reg <= trunc_ln70_1_reg_308_pp0_iter2_reg;
        trunc_ln70_1_reg_308_pp0_iter4_reg <= trunc_ln70_1_reg_308_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((icmp_ln69_fu_153_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j = 21'd0;
    end else begin
        ap_sig_allocacmp_j = j_1_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        pseudoimage_data_ce0_local = 1'b1;
    end else begin
        pseudoimage_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pseudoimage_data_ce1_local = 1'b1;
    end else begin
        pseudoimage_data_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        pseudoimage_data_we0_local = 1'b1;
    end else begin
        pseudoimage_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln69_fu_159_p2 = (ap_sig_allocacmp_j + 21'd1);

assign add_ln70_fu_169_p2 = (empty + trunc_ln70_fu_165_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln70_1_fu_230_p1 = grp_fu_406_p_dout0;

assign bitcast_ln70_fu_193_p1 = trunc_ln70_2_fu_189_p1;

assign bitcast_ln71_1_fu_234_p1 = grp_fu_125_p2;

assign bitcast_ln71_fu_209_p1 = trunc_ln5_fu_199_p4;

assign bitcast_ln72_1_fu_238_p1 = grp_fu_129_p2;

assign bitcast_ln74_fu_242_p1 = grp_fu_133_p2;

assign bitcast_ln75_fu_246_p1 = grp_fu_137_p2;

assign grp_fu_129_p0 = trunc_ln6_fu_215_p4;

assign grp_fu_406_p_ce = 1'b1;

assign grp_fu_406_p_din0 = bitcast_ln70_fu_193_p1;

assign grp_fu_406_p_din1 = avg_x;

assign grp_fu_406_p_opcode = 2'd1;

assign icmp_ln69_fu_153_p2 = ((zext_ln69_fu_149_p1 == pseudoimage_count_load) ? 1'b1 : 1'b0);

assign or_ln75_4_fu_250_p7 = {{{{{{bitcast_ln75_fu_246_p1}, {bitcast_ln74_fu_242_p1}}, {bitcast_ln72_1_fu_238_p1}}, {bitcast_ln71_1_fu_234_p1}}, {bitcast_ln70_1_fu_230_p1}}, {trunc_ln70_1_reg_308_pp0_iter4_reg}};

assign pseudoimage_data_address0 = pseudoimage_data_addr_reg_302_pp0_iter4_reg;

assign pseudoimage_data_address1 = zext_ln70_fu_175_p1;

assign pseudoimage_data_ce0 = pseudoimage_data_ce0_local;

assign pseudoimage_data_ce1 = pseudoimage_data_ce1_local;

assign pseudoimage_data_d0 = or_ln75_4_fu_250_p7;

assign pseudoimage_data_we0 = pseudoimage_data_we0_local;

assign trunc_ln5_fu_199_p4 = {{pseudoimage_data_q1[127:64]}};

assign trunc_ln6_fu_215_p4 = {{pseudoimage_data_q1[191:128]}};

assign trunc_ln70_1_fu_185_p1 = pseudoimage_data_q1[255:0];

assign trunc_ln70_2_fu_189_p1 = pseudoimage_data_q1[63:0];

assign trunc_ln70_fu_165_p1 = ap_sig_allocacmp_j[19:0];

assign zext_ln69_fu_149_p1 = ap_sig_allocacmp_j;

assign zext_ln70_fu_175_p1 = add_ln70_fu_169_p2;

endmodule //calculate_pseudoimage_calculate_pseudoimage_Pipeline_assign_loop
